### PR TITLE
[READY] Adds Syndicate Jobs hud icons.

### PR DESCRIPTION
**Pull request by EgorDinamit**
## About The Pull Request

What the header says.

## Why It's Good For The Game

Screenshot_76

## Changelog
:cl:
add: Added sec-hud icons for syndicate jobs.
/:cl:

### CODE REVIEW

**Comment by TheSwain** [comment]
Curious how this works - are the HUD icons in the mirror .dmi file? I don't see that file accessed anywhere in the code you edited.

**Comment by EgorDinamit** [comment]
@TheSwain 
Deputy hud icon is in this file and it is working.

**Comment by EgorDinamit** [comment]
Give me a moment, I'll fix some stuff here.

**Comment by EgorDinamit** [comment]
@TheSwain alright, it's working now.
I'd add a global list for all Fulp jobs later, in case my stupid solution is good enough.

**Pull request merged**
