### PR TITLE
ERPs Hear the Power Rangers theme on spawn

### PR DESCRIPTION
**Pull request by SgtHunk**
## About The Pull Request

See title

## Why It's Good For The Game

See title

## Changelog
:cl:
add: Added an Alert for ERP on spawn
soundadd: added ERT_Alert.ogg
/:cl:

### CODE REVIEW

**Comment by MaltVinegar** [comment]
Based

**Comment by JohnFulpWillard** [comment]
speed. merge. this. man.

**Review by JohnFulpWillard — APPROVED** [review]

**Review by EgorDinamit — CHANGES_REQUESTED** [review]
Make it play this music for **everyone** when they actually land at the station.

**Comment by SgtHunk** [comment]
Sounds like a good addition for this definitely serious pull request
Can try, don't expect anything though. Will look more in depth into it, but remember that this plays for all ERTs and subtypes  (Yes, CentCom officials and interns are also considered a ERT subtype so i should probably make it so it only plays out on actual ERTs

**Comment by ATH1909** [comment]
I got excited for a moment there because I misread the title as this playing for Emergency Response Parties, not ALL Emergency Response Teams, but then I read it properly.

Would it be possible to play this for just ERPs, then?

**Comment by SgtHunk** [comment]
There's always a way, and once I have time I'll see if I can add it so ERP plays it so that this PR has actual merge chance

**Comment by SgtHunk** [comment]
@ATH1909 there you go

**Comment by MaltVinegar** [comment]
ERP

**Pull request closed without merging**
