### PR TITLE
Load Mentors

### PR DESCRIPTION
**Pull request by dleetr**
## About The Pull Request
I didn't see load_mentors ever called, so I tried calling it in world.dm and it seemed to work on my local.

## Changelog
:cl:
fix: Mentors should actually load now
server: Update the mentor list in the file
/:cl:

### CODE REVIEW

**Comment by TheSwain** [comment]
That's interesting. But even after load, does this actively do anything?

**Comment by remove32** [comment]
I tried to test this one on the test server and it didn't seem to do anything

**Comment by dleetr** [comment]
On my local the global mentor_datums (or just mentors? One of them at least) populates a list of mentors correctly from the mentors file. I received the mentor verbs as a non admin on my local which I tested via hosting via my PC as guest and connecting through my laptop with my BYOND login. I am perplexed as to how it is working on my local but not the test server.

If more functionality is needed after loading and correctly adding the verbs to the correct players, I am unsure of what it should be.

**Comment by TheSwain** [comment]
I'll merge anyway because I don't see this causing any harm

**Pull request merged**
