### PR TITLE
[READY] The Snowpiercer Shuttle

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

This pull request adds a brand new shuttle, the NTSS Snowpiercer! This shuttle is an expanded standard shuttle featuring a full medbay, engineering rooms, a chem pharmacy and 2 seperate cockpits, one for the Captain and the Heads of Staff.

Features include:

- Fully furnished medbay with 3 stasis beds, 3 surgical duffel bags,  
a blood freezer, a prosthesis limb container and complimentary NanoMed venders.
- A standard brig.
- A cockpit split into two, one section designated as the Captain's Quarters and the other as a standard cockpit. Both have the necessary computers to operate the shuttle.
- A chemistry pharmacy.
- Standard Engineering room with atmospherics section.

## Why It's Good For The Game

This shuttle will join the shuttle roster as a more expensive version of the standard shuttle that the crew may buy if the server is in higher pop. Since Fulp has been averaging over 100 players in the later hours (EST), larger shuttles have been needed to be able to facilitate all these crew members. With a furnished medbay, the shuttle can handle a large influx of patients that may arise from untimely bombings by those too eager for EORG. Sections like Command and Security are tucked away from the passenger sections and protect those in it from decompression, bombings and plasma floods.

## Changelog
:cl:
add: Added shuttle
add: Better description
:cl:

### CODE REVIEW

**Comment by PapaSejd** [comment]
http://imgur.com/gallery/dPkIUhY

Heres an image of the shuttle in the editor.

**Comment by PapaSejd** [comment]
image
Dont worry about that, it was just a dme file that shouldnt of been uploaded that I had to delete.

**Comment by ghost** [comment]
Here are some images:
image
^Shuttle in editor view
image
^main passenger area with the chem lab and front of medical in view
image
^engineering
image
^atmos
image
^All of medical
image
^security/Brig
image
^Cap's quarters
image
^Cockpit

**Comment by Samuuu3** [comment]
Test merged and works just fine. @remove32 Thoughts?

**Comment by ghost** [comment]
This has been replaced in favour of #378

**Pull request closed without merging**
