### PR TITLE
Adds new function on the Communications Console, allows any Mod+ to call ERT if requested

### PR DESCRIPTION
**Pull request by SgtHunk**
## About The Pull Request

NOTE: This was more of me messing around. It's not expected to be merged.

This adds the new Admin command "ERT" which instantly redirects to the Create Antagonist -> Emergency Response Team section.
This new command appears after the new Communications console function (which requires Captain level access) is used, called "Request CentCom Personnel". This allows Admins to send in ERTs and its subtypes. INCLUDING CentCom Officials.

image

## Why It's Good For The Game

image

Makes sending ERTs slightly easier, and makes requesting them a separate thing than simply contacting CentCom.

## Changelog
:cl:
add: Added "Request CentCom Personnel" function for Communications console.
add: Added "ERT" Admin command to go with the mentioned above function, in case the higher ups wish to send any ERT and its subtypes (ERP, CentCom Official, Interns, etc)
/:cl:

### CODE REVIEW

**Comment by E231kei500bandai** [comment]
I dont really understand, why not just click "Send message to centcom" and type in we need ert

**Comment by E231kei500bandai** [comment]
you should add the ERT button to the "Send message to centcom" too

**Comment by SgtHunk** [comment]
Simply because the CentCom message is for more in-general usage
Also, if I added this to the CentCom message function instead then mods could call ERT on any centcom message
Which feels... rather like  a flaw. With this button, atleast now someone will have to specifically request for a Mod to call any subtype of ERT. Instead of y'know, waiting for an Admin Candidate+ or being able to call one because someone requested something simple using the normal message function.

**Comment by E231kei500bandai** [comment]
i dont really understand fulp why cant mods call the ert why is that an admin only thing or whatever

**Comment by E231kei500bandai** [comment]
so mods can only spawn in an ERT when the captain clicks the request centcom personnel button thats dumb

**Comment by SgtHunk** [comment]
It's because it's a subtype of the "Create Antagonist" button
Letting mods create ERT through admin perms would also let them access the entirety of "Game - Events" 
If this does go through, then at least mods will be able to do things like spawn a CentCom Official or whatever subtype of ERT they wish

**Comment by manray0** [comment]
Not sure how this will work, considering mods don't have access to +SPAWN, would be keen for a testmerge

**Comment by SgtHunk** [comment]
this uses the same check for nuke code requests (which mods can INDEED use and give)

**Pull request closed without merging**
