### PR TITLE
Disables Wizard Summon Ghosts

### PR DESCRIPTION
**Pull request by GuillaumePrata**
## About The Pull Request 
Just that

## Why It's Good For The Game
Ghosts bad I guess?

## Changelog
:cl: Guillaume H. Prata
del: Removed Summon Ghosts from the list of spells a wizard can buy with some downstream trickery.
/:cl:

### CODE REVIEW

**Comment by Samuuu3** [comment]
Thank god

**Comment by TimeURSS** [comment]
Finally no more orbiting, view-annoying ghosts that give you out while hiding

**Comment by ATH1909** [comment]
wha

why

why would you hate summon ghosts

summoning ghosts is one of the most based things a wizard can do

it lets people participate in the round while dead

**Comment by ATH1909** [comment]
> Finally no more orbiting, view-annoying ghosts that give you out while hiding

if you don't want ghosts to orbit you as a wizard, just don't summon ghosts

**Comment by ATH1909** [comment]
your best and only reason for making this PR seems to be "ghosts bad"

how

I can't

wha

**Comment by GoldenAlpharex** [comment]
> your best and only reason for making this PR seems to be "ghosts bad"
> 
> how
> 
> I can't
> 
> wha

Well, first of all, it's very annoying when you're dealing with tickets on that round. Second of all, I heard it was causing runtimes and thus lag to have ghosts turned on. Thirdly, you can't turn the ghosts off afterwards. Like, it wouldn't be so bad if they disappeared as soon as the wizard died.

**Comment by JohnFulpWillard** [comment]
You can't hit people through the obvious ghosts so someone trying to fight the wizard with a bat just cant

**Comment by SgtHunk** [comment]
> You can't hit people through the obvious ghosts so someone trying to fight the wizard with a bat just cant

feature

**Pull request merged**
