### PR TITLE
Ranch bottles to add flavor to your food.

### PR DESCRIPTION
**Pull request by SkippuSetsuna**
## About The Pull Request
Adds ranch to the dinnerware vendor in the kitchen

## Why It's Good For The Game
I think the food selection as a whole is lacking, and want to continue adding more foodstuff in the future for more MRP interactions.

## Changelog
:cl:
add: Ranch condiment and reagent into the game
imageadd: 
image

/:cl:

### CODE REVIEW

**Comment by gonenoculer5** [comment]
Okay two questions:
-Does this add to nutritional value of food items its applied to?
-Does this add different taste flavor text when applied and consumed? (Havent reviewed the code yet so I can probably answer that myself)

**Comment by ATH1909** [comment]
> Okay two questions:
> -Does this add to nutritional value of food items its applied to?
> -Does this add different taste flavor text when applied and consumed? (Havent reviewed the code yet so I can probably answer that myself)

Yes to both questions, although the taste added is just "Ranch".

**Comment by remove32** [comment]
> 
> 
> > Okay two questions:
> > -Does this add to nutritional value of food items its applied to?
> > -Does this add different taste flavor text when applied and consumed? (Havent reviewed the code yet so I can probably answer that myself)
> 
> Yes to both questions, although the taste added is just "Ranch".

mmmm... Ranch flavored Ranch

**Comment by remove32** [comment]
your ranch condiment bottle that is spawnable via game panel is fucked, the bottle isnt there but the ranch is

**Comment by SkippuSetsuna** [comment]
> 
> 
> your ranch condiment bottle that is spawnable via game panel is fucked, the bottle isnt there but the ranch is

believe I found the issue and going to fix it.

**Pull request closed without merging**
