### PR TITLE
Removes His Grace.

### PR DESCRIPTION
**Pull request by ErwinSnowden**
## About The Pull Request

Notes out His Grace and most references to it, if fulp ever changes its eyes on what it perceives as "needlessly killing", this pull request can easily be reverted.

## Why It's Good For The Game

fallfromgrace
It's against the rules to use, so we can't have it in the game.

## Changelog
:cl:
del: His Grace has been removed.
/:cl:

### CODE REVIEW

**Comment by SgtHunk** [comment]
Wouldn't it simply be easier to ONLY note out the uplink datum that makes it available to chap traitors?
Noting out the status effects feel unnecessary IMO

**Comment by ErwinSnowden** [comment]
No, you see, it has NO PLACE on this server as it just encourages people who pick it up to go on a rampage and kill everyone, there are very clear rulings on this and His Grace has never been allowed as a weapon because of its destructive nature. The only people who would think otherwise would also think that admins only act on things they personally thought inconvenienced them, which is clearly not the case. After all, even with the objective to hijack the emergency shuttle, you're only allowed to kill people after the shuttle has been called, we can't risk such a thing ruining more rounds than it already has.

**Comment by SgtHunk** [comment]
I mean, by just noting out the uplink datum it will only be available through admin spawn, so in that case it will only be admin-only which makes it the **admin's** problem
And I'm 99% sure this isn't even a 100% removal, there's also a module file that marks the his grace ascension
Otherwise, setting it so it checks for DAGD/Hijack as objectives before making it available would work

EDIT: goddamnit looking at code in phone is harsh, it did also comment out the module file but either way, this feels like too much of a removal to what could simply be noting out
I'll look to see if I can make it check for martyr/hijack as alternative

**Comment by ErwinSnowden** [comment]
> I mean, by just noting out the uplink datum it will only be available through admin spawn, so in that case it will only be admin-only which makes it the **admin's** problem
> And I'm 99% sure this isn't even a 100% removal, there's also a module file that marks the his grace ascension
> Otherwise, setting it so it checks for DAGD/Hijack as objectives before making it available would work

It's a problematic item that is directly prohibited by our rules. The only situation where His Grace would be feasibly allowed is as a nuclear operative or someone with the objective to die a glorious death, which the latter I'm considering removing as it only allows people to murderbone everyone. If the rules change, His Grace can be added back in but until that happens, we can't have items that directly encourage people to go on murder sprees that ruin the round for everyone else.

Also, we wouldn't want an admin accidentally spawning in this item under the pre-tense that its something else, that could de-rail the entire round over a misconception.

By the way, I can't seem to find this module file that marks ascension for His Grace, if that is true, could you please link it so I can note it out in a timely manner?

**Comment by SgtHunk** [comment]
On the file aspect, it's fine. Checking commit files on phone isn rough
although noting out the item + datum from the uplink would have been enough

I'm sure that admins know not to spawn items like that. Hell, it's common sense.
Otherwise, it serves as a good item for bus rounds/a madlad nuke op who tc traded.
Removing it like this shouldn't really be the way considering the only way _to reliably get this item is being a traitor chaplain_, and there is no other way apart from admin intervention.
I'd say simply noting out datum should do the job, admins know better and _assuming_ that they'll mess up by spawning the green bad murder toolbox feels like quite the null chance scenario

**Comment by ErwinSnowden** [comment]
You'd think they wouldn't consistently spawn archaic jungle megafauna capable of instantly gibbing people by going over their turf during a stun or resting period, yet they still do, clearly you haven't had adequate experience of our staff events. It's not a very descriptive path, just being "his grace", not many people know a lot about it.

**Comment by SgtHunk** [comment]
I mean, that scenario was an _admin event_ with a neutral _sentient_ junglefauna that only attacked if someone else did.
Admins _dont_ spawn a lot of stuff for _no reason_, and seeing how specific of an item His Grace is, along with the amount of mentions it gets because of its capability and overall being one of the unique traitor chap items, it would take a _very_ specific scenario, you won't see junglefauna on a consistent basis, apart from that one **bus round**. noting it out from uplink datums makes it so it will have to fit the same criteria of _admun intervention_.

**Comment by ErwinSnowden** [comment]
Actually considering closing this and just removing Conspicious and dangerous weapons from the traitor uplink in general, of course clown operatives will still have them. They're used solely for murderbone and really contribute nothing towards the game of actual value. After all, traitors and IAAs are supposed to be sneaky, aren't they?

**Comment by SgtHunk** [comment]
Traitors choose their playstyle, IAAs are supposed to be traitor-ish and a bit sneaky.
The Dangerous Weapons section holds a great amount of items, and honestly it's worth even as a non-hijack traitor because who wouldn't want a fun 30 damage sword to quickly dispose of their target.

**Comment by ErwinSnowden** [comment]
It always ends up being grab energy-bow, grab energy sword, kill 30% of the station crew before you get stunbatonned and then security powergames the traitor gear. It really has no place on fulp and to the people who don't want it, there are always other servers which have more relaxed regulations around antagonists but we're an MRP server, we should try to promote the best environment to foster roleplay.

**Comment by SgtHunk** [comment]
I mean, that sounds like a great hijack attempt/dagd.
Congrats to the lad who managed to kill 30% of the crew on a 150pop server.
Removing it as a whole only lessens the amount of gimmicks. 
Improve, don't remove.
A way to do this is adding checks for kill/dagd/hijack objectives and adding availability if so.

Also, as a side note. Wind is setting up a 2nd repo, so PRs are not getting merged and will have to be moved onto the 2nd repo once it's done being set up.

**Comment by ErwinSnowden** [comment]
> I mean, that sounds like a great hijack attempt/dagd.
> Congrats to the lad who managed to kill 30% of the crew on a 150pop server.
> Removing it as a whole only lessens the amount of gimmicks.
> Improve, don't remove.
> A way to do this is adding checks for kill/dagd/hijack objectives and adding availability if so.
> 
> Also, as a side note. Wind is setting up a 2nd repo, so PRs are not getting merged and will have to be moved onto the 2nd repo once it's done being set up.

This type of needless murder is only allowed after the shuttle is called. (In the case of defending murder by merit of objectives.)

Gimmicks that are against the rules frankly aren't welcome on our server and should be taken elsewhere.

**Comment by SgtHunk** [comment]
It's also allowed if it can **force** a shuttle call.
Luring megafauna onto station is a good way to do so.
Removing an entire section because "muh murderbone" is bad.
Someone might want to simply buy a revolver to take out their target in 2 clean hits and nothing else.
Also sleepy pen + esword is a strat, which is sneaky-ish while using an item from the section.

**Comment by ErwinSnowden** [comment]
> It's also allowed if it can **force** a shuttle call.
> Luring megafauna onto station is a good way to do so.
> Removing an entire section because "muh murderbone" is bad.
> Someone might want to simply buy a revolver to take out their target in 2 clean hits and nothing else.
> Also sleepy pen + esword is a strat, which is sneaky-ish while using an item from the section.

That way of approaching objectives does not foster roleplay befitting of an MRP server. Ideally, a traitor should peacefully convince the crew not to take the shuttle in order for a successful hijack to take place, or the objective as a whole should be removed.

**Comment by SgtHunk** [comment]
Grudgecode moment

**Comment by ErwinSnowden** [comment]
> Grudgecode moment

I've never once died to His Grace (on the opposite end), if you haven't picked it up, this was some horrible amalgam of satire about how the server is inherently not LRP and how the restriction of features based on some arbitrary notions is a poor decision especially when it's a very rare occurrence. 

Though clearly this is something that the rules and staff would support as it just causes issues for them, I have plans to rework or even completely phase out weaponry from the codebase in the inevitable shift into HRP gameplay which Fulpstation clearly needs, it could also serve well to cut off from the (vehemently racist) upstream who are negatively effecting the game by fostering a level of content unbecoming for our players and our rules as a server.

**Comment by SgtHunk** [comment]
I know, I was literally **there**
I even waited to see this PR up when you said you were gonna do it to prove a point
The shift of MRP was done purely rule-wise, probably because Fulp at the time of transition didnt have the manpower in the form of coders to actually implement more regarding that (which it still doesn't, sadly, but there's  a bit more than before)
I mean, removing an entire item purely because you killed people after activating it when you had _two steal objectives_ then proceeded to get hardcrit by a shocked grille because you had no insuls then getting banned over it does sound like grudgecode

**Comment by ErwinSnowden** [comment]
Something something, comment about regret

**Comment by ATH1909** [comment]
> I know, I was literally **there**
> I even waited to see this PR up when you said you were gonna do it to prove a point
> The shift of MRP was done purely rule-wise, probably because Fulp at the time of transition didnt have the manpower in the form of coders to actually implement more regarding that (which it still doesn't, sadly, but there's a bit more than before)
> I mean, removing an entire item purely because you killed people after activating it when you had _two steal objectives_ then proceeded to get hardcrit by a shocked grille because you had no insuls then getting banned over it does sound like grudgecode

To be fair, if he DIDN'T kill people with it once he had activated it, he'd have died horribly.

**Pull request closed without merging**
