### PR TITLE
Plasmaman gloves

### PR DESCRIPTION
**Pull request by Buzzardman2**
Hello and welcome to another buzzardman2's really crappy coding adventures. I found the code that changed plasmaman gloves and decided to try reverting it. Basically this will hopefully fix the code from burning you alive if you take your gloves off.

### CODE REVIEW

**Comment by TheSwain** [comment]
@remove32  Is this a desirable update?

**Comment by Buzzardman2** [comment]
Well i only know of a select few plasma men players but the ones i do know of were quite upset about the glove update. It's hard enough being a plasma man in the game when you take double damage, your suit and helmet are required or you'll burn to death. The gloves being a requirement to not burn to death makes it even harder to stay alive as a plasma man especially with the high likelihood of assistants stealing your insulated gloves. The old suit used to have a thin under-glove as part of the main suit but the recent change made it so they have to have gloves on in the glove slot instead.

**Comment by TheSwain** [comment]
Has this update been tested extensively?

**Comment by Buzzardman2** [comment]
Well i did test it to make sure it worked but i don't think i'd use the term extensively. All i did was remove the part of the code that says it needs gloves to extinguish the fires on a plasma man suit which was how it originally was before the PR request to change them was approved on tg.

**Comment by ATH1909** [comment]
To clarify, this change was initially added because the plasmaman envirosuits actually DON'T cover your hands by default, and making them do so causes them to cover up your gloves or something, IIRC.

https://github.com/tgstation/tgstation/pull/49406

**Comment by pireamaineach** [comment]
This doesn't actually affect gameplay in any meaningful way from all gameplay I've seen on /tg/.

If an assistant steals your insuls and kills you, that's an administration issue.

**Comment by Buzzardman2** [comment]
Yeah because TG has like half our player base and probably a lot more admins on to deal with it so it's hard to compare our server with theirs. The point of doing it on fulp was to reduce instances of it happening in our server not TG. TG isn't changing it anytime soon and i didn't recommend it to be changed on there this is for fulpstation only so i also don't see how their gameplay loop is going to effect our decisions for our server. 
This also isn't about being good or bad at the game it's about a function TG added that i felt wasn't really needed as plasma men have enough issues to deal with without having to worry about trying to change gloves without burning to death or assistants and antags stealing their gloves causing them to be out of the round. 
No one really said this was going to be implemented either as it's usually up to swain to make that choice but i and a lot of our other plasma man mains on fulp have hated this change and it was what motivated me into fixing it.
Also i wanted to mention that my changing this is in no way an insult to you or your code it was just to help improve our server for the people who do play plasmaman on it.

**Comment by ATH1909** [comment]
> or assistants and antags stealing their gloves causing them to be out of the round.

My concern is less with random assistants mugging you, and more with fulpsec taking your gloves or fulpdoctors reviving you without your gloves.

**Comment by TheSwain** [comment]
@Buzzardman2 Alright, I'd give this update a trial run. BUT, make sure to leave a // FULP EDIT comment next to any line you've adjusted inside of TG's core files, along with a short note about the change. This is how we know that a change was made if there is a conflict with TG down the line.

**Comment by Samuuu3** [comment]
Most plasmaman players I talk to seem to want this change.

**Comment by Samuuu3** [comment]
Test merged this and it works as designed and nothing seems out of the ordinary.

**Comment by Samuuu3** [comment]
@TheSwain

**Pull request merged**
