### PR TITLE
[DO NOT MERGE] TG update.

### PR DESCRIPTION
**Pull request by EgorDinamit**
### Keeping it up to date with orange upstream.

Helping Swain with 1889 commits.

### CODE REVIEW

**Comment by JohnFulpWillard** [comment]
you mean to say this man isn't the head maintainer? why?

**Comment by BootlegBow** [comment]
when this gets merged all the full players are gonna get really confused with the huge dump of new content

**Comment by SgtHunk** [comment]
Hire this MAN
Make him head maintainer rn

**Comment by BootlegBow** [comment]
is it possible to remove some of the commits, so that we don't get the fucky /tg/ stuff and only the good parts?

**Pull request closed without merging**
