### PR TITLE
Fixes the description of wintercoats.dm

### PR DESCRIPTION
**Pull request by AtlasRules**
## About The Pull Request
Capitalises the description of the command Winter Coats that Cosmic made.

## Why It's Good For The Game

because OCD reasons

## Changelog
:cl:
A typo with the head of department's winter coats has been fixed in newer models. ~ NT
/:cl:

### CODE REVIEW

**Comment by TheSwain** [comment]
i'm trying to figure out why it says the entire file has been changed, and not just the descriptions

**Comment by CosmicPhoenix** [comment]
#141 invalidates this, I had to change the sprites so I bundled it in with the typo fix.

**Comment by TheSwain** [comment]
image

merged 141, but it still says the entire file has been changed.

**Comment by ghost** [comment]
@TheSwain he fucked up the line endings by using the web editor.

**Comment by ghost** [comment]
Nevermind, he just added a new file to the fulpstation section, which overrides the old one.

**Comment by TheSwain** [comment]
lol ahhh, thx @Qustinnus 

Closing since Cosmic's update fixed this

**Pull request closed without merging**
