### PR TITLE
Improved Detective Default Kit

### PR DESCRIPTION
**Pull request by Surrealaser**
## About The Pull Request

This PR adds several new toys to the detective's default kit:

1: Detective scanner glasses. This has a meson and standard mode. Has integrated diagnostic, health and sec HUDS. Analyzes reagents. Can be made in the protolathe but requires sec access and is expensive. It is not flashproof despite appearances.
2: Detective PDA cartridge gains access to atmospheric and reagent scanning functionality.
3: Detective starts with crew pinpointer and portable crew monitor for help tracking suspects/sec personnel/victims.
4: Detective starts out with a fully loaded high capacity detective camera and universal recorder.
5: Forensic scanner now has a biochem scanner mode that scans reagents in a body and has the functionality of an advanced health scanner. Cost of manufacture has been increased to compensate for additional functionality. Records of all scans are saved to the scanner's log and can be printed.

## Why It's Good For The Game

Substantially improves the detective's ability to fulfill his role and do his job, giving him immediate and guaranteed access to much needed tools.

## Changelog
:cl:
add: Detective default kit expanded, and now includes detective scanner glasses, a high capacity camera, universal recorder, crew pinpointer and portable crew monitor.
add: Forensic scanner now has a biochem scan mode that acts like an advanced health analyzer; scan results are saved to its log and can be printed.
add: Detective scanner glasses added: Features health, sec and diagnostic HUD and reagent scanning with toggleable mesons. Can be temporarily disabled with EMPs. Is not flash proof.
/:cl:

### CODE REVIEW

**Comment by GuillaumePrata** [comment]
More tools for investigation are good, hopefully Detectives will spend more time doing their unique job at sec, Investigation, than Validhunting like a noir Sec Officer.

**Comment by ghost** [comment]
Forensic scanner defo had the functionality to check chems and I'm pretty confident it worked as a health scanner too already at one point, are you 100% that's not the case any more with the existing item?

Also I'm not sold on the idea of the detective, who formerly just got regular-ass shades, now getting the single most robust eyewear outside of xray and thermal shit in the game. That seems like a huge balance shift and if most of the functionality, like diagnostics, could be added as a non-eyewear scanner or put into the forensic scanner I'd be way more on board with it.

The rest of it I like though.

**Comment by ghost** [comment]
Oh and the code looks fine, intrusion is minimal, I take it it's mostly copypasted procs from existing items which is fine, so green light on that side @TheSwain

**Comment by Surrealaser** [comment]
@Mithrandalf The forensic scanner has a reagent scan functionality, but it only works on objects, not people/bodies. It does not and to my knowledge never had a health scanner capability.

As to the eyewear, it's strong, but all it does is provide information and remote record access, versus something mechanically strong like xrays and thermals. Given how fast paced Med-RP is, the detective needs potent tools that are time efficient in order to property do his job in a timely manner. Minting more of these is prohibitively expensive, and comes at a great opportunity cost, which compared to a lot of the better things you can print with the sec protolathe, will definitely give you pause at the least. Generally I don't see how adding health, diagnostic and mesons to the typical secglasses the Detective usually has will break things.

Also yes, some copy pasta was involved regarding the scanner health analyzer logging to minimize code intrusion.

**Comment by ghost** [comment]
These sunglasses, that every detective will get, for free, as they spawn, have all the advantages of mesons, sunglasses, SecHUDs, science goggles and MedHuds in a single item. These sunglasses might not be as good as thermals for murderbone reasons, but it's really not contraversial to say they will become the single most valuable eye-slot item on the station z-level at roundstart. That is a massive upgrade from 'not even sechud sunglasses' and it's something that needs consideration.

Do they require any tech researched before more can be made?

**Comment by Surrealaser** [comment]
@Mithrandalf Yes, the research that unlocks HUD creation with the protolathe. The real barrier is the cost though.

Having said that, you're definitely going to have to choose between making these and printing weapons and other high level goodies given the cost, and to be honest, I'd probably rather have the beam rifles and such.

**Comment by GuillaumePrata** [comment]
If balance is a issue, removing the Flash proof from the glasses could be interesting, now the Detective is more susceptible to some stuns and trade it for increased info, also removing the Flash proof makes it a less desirable tool for antagonists.

**Comment by BLUREMOTE** [comment]
If we do get such a good hud like this, it gotta be toggleable so you dont have every huds at once: you gotta select which hud you wanna use and can only use on at a time.

**Comment by Surrealaser** [comment]
@GuillaumePrata I really like that idea actually; undermines its value for antags and helps keep the Detective in the investigative lane as opposed to being a glorified SO.

**Pull request closed without merging**
