### PR TITLE
[READY] Removes security.

### PR DESCRIPTION
**Pull request by ErwinSnowden**
## About The Pull Request

code doesn't run, doesn't compile and is broken, i deleted security.

## Why It's Good For The Game

security killed me as a friendly antagonist without an authorized execution. i'm showing them that they need to improve their roleplay and until we get a whitelist system in, we have to do this.
## Changelog
:cl:
del: Removes security.
balance: Security is gone, now you will be forced to roleplay in order to survive.
/:cl:

### CODE REVIEW

**Comment by ATH1909** [comment]
based

**Comment by remove32** [comment]
fix the changelog.html conflict and i'll speedmerge this

**Comment by ATH1909** [comment]
> fix the changelog.html conflict and i'll speedmerge this

even based-er

**Comment by Ratvarr** [comment]
this is funny AF, and based

**Comment by FatCat919** [comment]
merge. i want to dominate the station as antag every shift, pls remove sec so i have no resistance to this. amen. based.

**Comment by ATH1909** [comment]
> merge. i want to dominate the station as antag every shift, pls remove sec so i have no resistance to this. amen. based.

Unfortunately, you'll still have a source of at least some resistance: admins.

**Comment by ATH1909** [comment]
image

image

fulpcoders.jpg

**Comment by remove32** [comment]
we've had our fun

**Pull request closed without merging**
