### PR TITLE
Engiborg Basic Manipulator and Upgrade Added

### PR DESCRIPTION
**Pull request by Surrealaser**
## About The Pull Request
Adds a basic manipulator to the engiborg that can hold and use wall mounted frames and basic electronics.

The manipulator upgrade for the engiborg expands the functionality of the manipulator to handle circuit boards, stock parts, air/plasma tanks and vending machine refills.

## Why It's Good For The Game

Gives the engiborg basic functionalities it should have, but locks more advanced elements behind upgrades.

## Changelog
:cl:
add: Adds a basic manipulator to the engiborg that can hold and use wall mounted frames and basic electronics.
tweak: The manipulator upgrade for the engiborg expands the functionality of the manipulator to handle circuit boards, stock parts, air/plasma tanks and vending machine refills.
/:cl:

### CODE REVIEW

**Comment by ATH1909** [comment]
Just so you know, engiborgs can already attach frames to walls by click+dragging them onto the wall, IIRC.

Then again, I can't find the code for how that works, and it might just be a rumor. Some testing might need to be done.

**Comment by Surrealaser** [comment]
@ATH1909 I know. This is a more convenient and intuitive way of handling them.

**Comment by remove32** [comment]
@TheSwain I remember testing this on the test server - pretty sure it went fine and can probably be merged. we can test it on the test server again though

**Comment by TheSwain** [comment]
Merging other PRs probably created some issue with a var somewhere. i'll merge as soon as that gets tweaked

**Comment by Surrealaser** [comment]
@TheSwain Sounds good, I'll fix this soon.

**Comment by Surrealaser** [comment]
@TheSwain Ready to go.

**Pull request merged**
