### PR TITLE
Adds Soap to Mediborg

### PR DESCRIPTION
**Pull request by Surrealaser**
### About The Pull Request
Gives the mediborg soap so it can actually disinfect surfaces and help stop the spread of disease instead of having to spam chem to do so.

### Why It's Good For The Game
As a mediborg, you currently have two options:

1: Waste chem charge to clean medbay in a tedious way with droppers, beaker spilling and/or hygiene foam bombs.

2: Let Medbay become a festering, disease spewing nightmare of blood and puke.

This change essentially adds some QoL to the Medborg, making spot cleaning less cancerous, without giving the borg module a capability it doesn't already have, and without treading on the toes of the Janiborg who cleans far more efficiently.

### Changelog
🆑
add: Mediborgs can finally use soap to clean up disease bearing blood, puke and mucus.
/🆑

### CODE REVIEW

**Comment by remove32** [comment]
Why not have the janitor clean it up
or a janitor bot
or ask robotics for a bot or use the one in medbay

**Comment by Surrealaser** [comment]
@remove32 Mainly because by the time the janitor drops by, or the cleanbot has done its job, tons of people have already been infected by walking over diseased blood/puke.

**Comment by remove32** [comment]
> 
> 
> @remove32 Mainly because by the time the janitor drops by, or the cleanbot has done its job, tons of people have already been infected by walking over diseased blood/puke.

could have chemist make cleaner grenades or soap. med has a lot of stuff they can do to clean. feels like it might be a bit much but i'm interested to hear what others think

**Comment by Surrealaser** [comment]
@remove32 It should be noted that you can already do foam reactions using beakers; it's actually more efficient than using soap when you need to mass clean. You can also spot clean by spilling/slashing space cleaner mixes 1U at a time. This is primarily QoL.

**Comment by remove32** [comment]
well, if swain's ok with it then whatever. 
the soap is indeed there, tested just fine. 
does this soap ever get used up or is it just infinite?

**Comment by remove32** [comment]
@Surrealaser can you resolve the conflict on this? i'll merge once thats done

**Comment by SpacingNevada** [comment]
This seems like a reasonable idea. It's unlikely that this will put janitors/janiborgs out of much work but it will allow mediborgs to more easily achieve their function which is presumably to promote the good health of the crew.

**Pull request closed without merging**
