### PR TITLE
Adds Caleb's and Dusk Dude's outfit

### PR DESCRIPTION
**Pull request by AtlasRules**
## About The Pull Request

Adds Caleb's outfit and Dusk Dude's beard to the game, for the Halloween event.

## Why It's Good For The Game

Now you can kick cultist ass in style. Also is a cool Halloween costume, I guess.

## Changelog
:cl:
After archaeological digs in Massachusetts and Arizona, a strange outfit have been found. They have added to the list of acceptable Halloween costumes. ~ NT  
/:cl:

caleb+duskdude

### CODE REVIEW

**Comment by AtlasRules** [comment]
Caleb but spessman is useless, so please delete that.

**Comment by AtlasRules** [comment]
begone

**Comment by TheSwain** [comment]
Looking good - get those files in the appropriate Fulpstation folder for .dm and .dmi files respectively, and we'll merge this in. Mith can show you where they need to go.

**Comment by AtlasRules** [comment]
actually, I'll close this and upload the whole lot of outfits I plan to make.

**Pull request closed without merging**
