### PR TITLE
Forgottenship Ruin - rebalance, config update, uplink item.

### PR DESCRIPTION
**Pull request by EgorDinamit**
_Porting my PR from tg-station, aye._
https://github.com/tgstation/tgstation/pull/50529

## About The Pull Request

Cybersun Hardsuit is added to nuke ops and traitors uplinks.
Cybersun Hardsuit armour values changed to: _(**"melee" = 30**, **"bullet" = 40**, "laser" = 70, **"energy" = 70**, **"bomb" = 30**, "bio" = 100, **"rad" = 60**, **"fire" = 60**, "acid" = 60)_
Turrets placed on the ship now have a higher rate of fire. 
Instead of 50 sheets, only 15 spawn near generator. 
Captain's empty sleeper can't be destroyed to prevent it from emitting GPS signal anymore.

## Why It's Good For The Game

Balance, Config policy and etc.

## Changelog
:cl:
add: Cybersun hardsuit added to traitors(14TC) and nuke ops(8TC) uplinks.
tweak: Adds and replaces a few items on the ship, such as firing pins, materials and encryption keys.
tweak: Cost and weight values of most space ruins changed.
balance: Cybersun hardsuit armour values increased.
balance: Syndicate ship ruin turrets armour and rate of fire changed.
fix: Empty sleeper, that emits GPS signal is now indestructible.
config: Adds config to edit "important_info" for both, crewmembers and captain of forgotten ship ruin.
/:cl:

### CODE REVIEW

**Comment by Samuuu3** [comment]
Since this was merged to TG we should get it once we get back to being forked to them right?

**Comment by TheSwain** [comment]
@Samuuu3 yes correct!

**Comment by EgorDinamit** [comment]
@TheSwain so it is forked back.
Check PR if you need anything else to be done.

**Comment by EgorDinamit** [comment]
Just noticed, Fulp is already up to date with TG.
If there is anything specific needed to be made, I'll open another PR.

**Pull request closed without merging**
