### PR TITLE
Nuke tools resprite

### PR DESCRIPTION
**Pull request by Ratvarr**
## About The Pull Request
makes a really small change with SM sliver and tongers from a tator objective
image
## Why It's Good For The Game
makes it a bit more aesthetically pleasing
## Changelog
:cl:
imageadd:nuke_tools.dmi SM shard from a glass shard that's yellow and the tongers to have blue at the grabby bits.
/:cl:

### CODE REVIEW

**Comment by ATH1909** [comment]
I don't really see how this is a "fix" (it's more of an "improvement", really), but hey, the new sprites look pretty good.

**Comment by Ratvarr** [comment]
eh, it's my first PR that doesn't do anything

**Comment by TheSwain** [comment]
The problem with altering TG's .dmi files is that they'll be replaced the moment TG makes a change to the same file.

**Comment by Samuuu3** [comment]
I like the sprites but yeah altering TG's .dmi is going to probably get yours overwritten in the future.

**Comment by Ratvarr** [comment]
IDK what else I gotta do but I have that now

**Comment by EgorDinamit** [comment]
@MajorMeltdown you may try to make this PR for tg.
Those sprites look pretty nice.

**Comment by Ratvarr** [comment]
im banned from TG so idk if they would even take my PR, plus they are waaaaaaay bigger then this
I cant do that due to the fact they could just out right get rid of anything I would try, its TG
they are crazy with code
I think way to far ahead

**Pull request closed without merging**
