### PR TITLE
Moved syringe guns from storage to CMO

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

Deletes the two syringe guns in medical storage on boxstation, adds one syringe gun to the CMO's office.

## Why It's Good For The Game

Syringe guns literally exist for shitty powergaming for the first medic/chemist/clown who can grab them. This way it's under the CMO's control.

## Changelog
:cl:
tweak: The CMO now has access to medbay's only syringe gun.
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
If this gets merged and goes down well, it shouldn't be hard to make sure it's the case for the other maps.

**Comment by AtlasRules** [comment]
The amount of times I’ve seen a greyshit break into medbay, steal the syringe gun, needles and a bottle of toxins is insane.

**Comment by FrankySparnar** [comment]
Imagine not getting assblasted by a rando with chems

**Comment by TheSwain** [comment]
I think I would want to include another syringe gun or two elsewhere, someplace under lockdown. Security medical ward, and maybe virology? Someplace besides easy-access medical.

**Comment by TheSwain** [comment]
I need to confirm whether or not changing a .dmm file will be overwritten by future TG changes to the same file, before I merge anything.

**Comment by ghost** [comment]
Honestly not sure if it'll get overwritten. One easy way to find out.

**Comment by TheSwain** [comment]
Yeah looks like it'll be overwritten the next time TG makes a change. Better to push this change to TG so it applies forever, and see if they'll accept it.

**Pull request closed without merging**
