### PR TITLE
Adds Medical Skill

### PR DESCRIPTION
**Pull request by JohnFulpWillard**
## About The Pull Request

Adds Medical Skill to the game a way of encouraging doctors to do surgery rather than throwing someone in cryo or giving them a patch and throwing them out. This PR also brings back the Legendary Medical skill cloak for those who do enough surgeries!

(Note: This was edited over /tg/ code rather than its own fulp-only. I dont think it's possible to change that since medical EXP is given and defined in every separate surgery)

## Why It's Good For The Game

Medical EXP was extremely useful in not making medbay extremely slow, and recently medbay has been overflowing with dead bodies and taking 15 minutes to tend wound a single dead body is painful. Also, more skills and things to do is always fun.

## Changelog
:cl:
add: Medical EXP
add: A way to get the Medical cloak
/:cl:

### CODE REVIEW

**Comment by AlucardHellsingChapel** [comment]
Maybe add to legendary medical skill abbility to make 2 surgeries at same aka worse version of lavaland Staff from chest

**Comment by JohnFulpWillard** [comment]
Once we update to /tg/, I'll see if I can replace this PR with a medical skillchip that makes your surgeries faster

**Comment by ATH1909** [comment]
You might wish to review the reasons why the healing skill was removed from the game: https://github.com/tgstation/tgstation/pull/52005.

**Comment by JohnFulpWillard** [comment]
> 
> 
> You might wish to review the reasons why the healing skill was removed from the game: [tgstation#52005](https://github.com/tgstation/tgstation/pull/52005).

in my opinion, fulp is /tg/ but just more advanced/powergamey. My main example to this is t5 parts, so I feel having medical skill just fits in with fulp more than /tg/.

**Comment by XanHiroki** [comment]
Franklin.

**Comment by AlucardHellsingChapel** [comment]
Merge this

**Comment by ATH1909** [comment]
> > You might wish to review the reasons why the healing skill was removed from the game: [tgstation#52005](https://github.com/tgstation/tgstation/pull/52005).
> 
> in my opinion, fulp is /tg/ but just more advanced/**powergamey**. My main example to this is t5 parts, so I feel having medical skill just fits in with fulp more than /tg/.

image
image

Fulp is many things, but a safe haven for 'gamers (like ourselves) isn't one of them.

**Comment by JohnFulpWillard** [comment]
> 
> 
> > > You might wish to review the reasons why the healing skill was removed from the game: [tgstation#52005](https://github.com/tgstation/tgstation/pull/52005).
> > 
> > 
> > in my opinion, fulp is /tg/ but just more advanced/**powergamey**. My main example to this is t5 parts, so I feel having medical skill just fits in with fulp more than /tg/.
> 
> image
> image
> 
> Fulp is many things, but a safe haven for 'gamers (like ourselves) isn't one of them.

I didn't mean powergamey in that way, I meant it as being advanced/experienced in your job to the point where you can carry the department (Like a T5 Ore silo and a good miner able to singlehandedly provide the station with all the mats they need (yes i know tg removed ore silo upgrades), or a doctor that can tend wound 500 brute/burn in half a minute)

**Comment by ATH1909** [comment]
> > > > You might wish to review the reasons why the healing skill was removed from the game: [tgstation#52005](https://github.com/tgstation/tgstation/pull/52005).
> > > 
> > > 
> > > in my opinion, fulp is /tg/ but just more advanced/**powergamey**. My main example to this is t5 parts, so I feel having medical skill just fits in with fulp more than /tg/.
> > 
> > 
> > image
> > image
> > Fulp is many things, but a safe haven for 'gamers (like ourselves) isn't one of them.
> 
> I didn't mean powergamey in that way, I meant it as being advanced/experienced in your job to the point where you can carry the department (Like a T5 Ore silo and a good miner able to singlehandedly provide the station with all the mats they need (yes i know tg removed ore silo upgrades), or a doctor that can tend wound 500 brute/burn in half a minute)

Okay, but the medical skill isn't a measure of how "advanced/experienced in your job" you are, it's a measure of "have you spent 20 minutes of this round essentially afking while tend wounds-ing a monkey who's continually taking damage".

**Comment by JohnFulpWillard** [comment]
> 
> 
> > > > > You might wish to review the reasons why the healing skill was removed from the game: [tgstation#52005](https://github.com/tgstation/tgstation/pull/52005).
> > > > 
> > > > 
> > > > in my opinion, fulp is /tg/ but just more advanced/**powergamey**. My main example to this is t5 parts, so I feel having medical skill just fits in with fulp more than /tg/.
> > > 
> > > 
> > > image
> > > image
> > > Fulp is many things, but a safe haven for 'gamers (like ourselves) isn't one of them.
> > 
> > 
> > I didn't mean powergamey in that way, I meant it as being advanced/experienced in your job to the point where you can carry the department (Like a T5 Ore silo and a good miner able to singlehandedly provide the station with all the mats they need (yes i know tg removed ore silo upgrades), or a doctor that can tend wound 500 brute/burn in half a minute)
> 
> Okay, but the medical skill isn't a measure of how "advanced/experienced in your job" you are, it's a measure of "have you spent 20 minutes of this round essentially afking while tend wounds-ing a monkey who's continually taking damage".

I used to only see that happen by one doctor every 4-5 rounds, and I don't see a problem with it. Fulp is highpop, so there's always another doctor to treat you, and the reward is that the doctor not treating people in the first 20 minutes end up treating double the amount of people for the rest of the round, and with Medical EXP, some people might want to start playing doctor again (like me and a few other ex-doctor mains)

Also, by "powergamey", I meant we're more fastpaced. We have t5, faster movement speed, and people usually don't like sitting around for more than 2 seconds

**Pull request closed without merging**
