### PR TITLE
Tgupdate

### PR DESCRIPTION
**Pull request by remove32**
## About The Pull Request
Pulling from TG's master!

## Why It's Good For The Game
Fixes for broken shit, new content, removing demo bullshit!

### CODE REVIEW

**Comment by Samuuu3** [comment]
Testmerged this and it seems to be working as designed.

**Comment by Samuuu3** [comment]
Some graphical issues here tho: https://github.com/tgstation/tgstation/issues/50875

**Comment by ghost** [comment]
How about you leave out the canister tier part of the updates so this update wont torture me / (us??) With having to upgrade canisters

**Comment by remove32** [comment]
> 
> 
> How about you leave out the canister tier part of the updates so this update wont torture me / (us??) With having to upgrade canisters

why shouldnt we get canister tiers? make a good case for me, not just "i dont like it"

**Comment by remove32** [comment]
> 
> 
> Some graphical issues here tho: [tgstation/tgstation#50875](https://github.com/tgstation/tgstation/issues/50875)

yeah, am aware of the graphical issues. waiting for TG to merge at least some fixes

**Comment by ghost** [comment]
Alright heres the thing about canister tiers:
Not everyone knows about them which may lead to explosions.
You cant upgrade already finished canisters afaik which makes it annoying to rebuild a canister each time just to upgrade it. 
Pipes and similar dont have limits, so why should canisters?

**Pull request merged**
