### PR TITLE
Reverting chat color for dark mode

### PR DESCRIPTION
**Pull request by Buzzardman2**
Reverting the change to the chat colors because there was nothing wrong with the colors to begin with.

### CODE REVIEW

**Review by Shadowtail117 — APPROVED** [review]
Yes yes a million times yes. You are my savior.

**Comment by AtlasRules** [comment]
I hate the new piss yellow command chat, I use dark mode for a reason damn it, thanks for the change

**Review by AtlasRules — APPROVED** [review]

**Comment by remove32** [comment]
Do you have a screenshot of this @Buzzardman2 ? the colors you listed look pretty dark, might be hard to make out against darkmode still

**Comment by remove32** [comment]
testmerged this just now. worked great.

**Review by remove32 — APPROVED** [review]

**Pull request merged**
