### PR TITLE
[READY] Total Rework of R&D Point Generation

### PR DESCRIPTION
**Pull request by jaw-sh**
This code is ready for peer review. It is being submitted to Fulp directly because Orange and other /tg/ maintainers do not want to discuss their R&D plans.

## About The Pull Request
This PR utilizes multiple RD servers for point generation and splits research points into department based categories. General research points can be used for all departments, but using multiple RD servers to research points in a single category have diminishing returns.

## Why It's Good For The Game
The Research Director is a eunuch position. Before moving Research to the RD's personal computers, he served no purpose at all. With these changes, he plays a more active role in actually directing research. This also positions the R&D so it's possible to play with active point generation again.

The commit also adds Malf AI and Traitor mechanisms to the RD server. What used to be a defunct room representing an old system is now a high-risk area of the R&D department that the RD should actively be checking for tampering. A lack of oversight can empower antagonists.

On its face, this change does not impact the flow of the game very much. The passive point generation is at the same rate as before. The change encourages the RD to direct research, encourages antag play in the RD server room, and paves the way to more inter-department research fun.

## Changelog
:cl:
refactor: RD Servers switched back to multi-server point generation.
add: RD Server terminal now displays room server is in.
add: Added a research point pool to each department.
add: All nodes now have a department whose point pool they draw from before drawing points from General Research.
del: Removed nanite research points. Nanite research uses Science research - and only Science research - instead.
add: RD Servers can now be assigned a department or left on General Research.
balance: RD Servers now lose 20% efficiency (multiplicative) per server tagged to the same department.
fix: Fixed RD Servers not generating heat.
balance: RD Servers lose efficiency depending on their temperature, and disperse temperature based on their tile's air mass in moles.
code: Moved some department colors over to constants.
add: Malf AI hacked APCs generate a processing power point on average once per 5 minutes per server.
add: Emagged RD servers are slaved to the emagger's uplink and generates 1 TC every 5 minutes and no longer generates research points. It takes 75m to refund an emag, 110m to buy Romerol.
balance: Alcohol is now an easier sweet spot to hit for passive RP generation.
/:cl:

## WIP
 - [ ] Need to test edge Research Point uses
 - - [x] ~Selling disks.~ This never worked apparently.
 - - [x] Dissection papers (4eeddfa63d5f33fcdee3fa8909eab735bbfbff3d)
 - - [x] SM radiation research.
 - - [ ] Tesla research.
 - - [ ] Singulo research.
 - - [x] Alcohol (fb18d8d4d6c5e3d7baf2643b5f1e473ebf2ffaaf)
 - - [x] Nanites (cf32d9fad71dcfcecd8e544dedc2430d84ac30a6)
 - [x] Need to restrict z-levels so that the occasional RD servers spawning in away missions do not count. (5db18c79f2fe0eef42ab5ba9758eaa24beabf794)

image
image
image

### CODE REVIEW

**Comment by jaw-sh** [comment]
RD server giving off sparks as it generates a processing power point for the malf AI controlling its APC.
image

**Comment by jaw-sh** [comment]
RD server now dispenses 1 or 2 TC every 10 minutes when emagged.
image

**Comment by jaw-sh** [comment]
I've rebalanced TC from emagged RD servers. A traitor can slave one RD server to their uplink, which gains 1 TC every 5 minutes. It takes 1 hour and 15 minutes to recoup the investment into their emag. It would take 1 hour and 45 minutes to buy Romerol. A traitor can only slave one RD server to their uplink, and a server can only have one uplink it is slaved to. Slaved RD servers do not produce RP, show department as UNKNOWN, and emit sparks every time they generate a TC.

**Comment by jaw-sh** [comment]
I'm having trouble testing the Singulo/Tesla RP generation but considering no one ever sets them up I'm also having trouble caring.

Is there anything else I should definitely check works before saying this is ready and writing my changelog?

**Comment by gonenoculer5** [comment]
As someone who wanted to personally rework R&D, the only thing you could do to make this any better would be to make R&D use TGUI, good work lad. 👍

**Comment by WarlockD** [comment]
Somone ported my simple (not a complete rework mind you:P) over to bee.
https://github.com/BeeStation/BeeStation-Hornet/pull/1724
It has a tgui menu if you want to take from that.

**Comment by Homingpenguins** [comment]
Does the emagged RnD console give a TC to every traitor? thats what it seems like from reading that syndicate channel announcement. even though that isnt the case with the 1 RnD console per uplink.

**Comment by jaw-sh** [comment]
No. That screenshot is old. When the server is emagged, it attempts to find the uplink device on the emagger. If it finds one, it binds to that. The uplink also binds to the server. If you attempt to emag another server, it will error. If you attempt to emag an emagged server, it will error. That one uplink will receive 1 TC every 5 minutes until the server is deconstructed.

**Comment by TheSwain** [comment]
Heads up on editing .dmm map files: The next time TG updates the same .dmm, your changes will get steamrolled instantly. Even though it shouldn't seem like that's what will happen, it does every time.

**Comment by jaw-sh** [comment]
Dunno what to do about that besides just aliasing the computer boards. That's the only thing changed. Oranges would never upstream this though.

**Comment by jaw-sh** [comment]
Alternatively, I could upstream just the removal of the production server board and the RD setting for access.

**Pull request closed without merging**
