### PR TITLE
DAMN YOU WORK

### PR DESCRIPTION
**Pull request by checkraisefold**
Refer to issue #0.

#### Intent of your Pull Request

stupid bracket

##### Changelog

:cl:
bugfix: Bracket that caused compilation to error, fixarino with this.
/:cl:

### CODE REVIEW

**Comment by checkraisefold** [comment]
@tomamoto merge this or it wont compile

**Comment by checkraisefold** [comment]
Also, theres an access error with the permamute fix. It wont work for now.

**Comment by tomamoto** [comment]
Access error?  Can you provide more details please (like the actual log line you're referring to)? Please test your code before submitting a PR from now on.

**Comment by checkraisefold** [comment]
@tomamoto If you could help, I dont know how to unmute the person. Tried a few things.

**Comment by tomamoto** [comment]
@checkraisefold The spawn() command may be more appropriate than sleep() to accomplish this.  If you placed the unmute command inside the spawn() block, that _should_ work.  I'm not extremely familiar with DM Language, but this seems more practical for a long wait like this to avoid potentially blocking other code execution.  http://www.byond.com/docs/guide/chap13.html

**Pull request merged**
