### PR TITLE
Sal chems

### PR DESCRIPTION
**Pull request by Saliferous**
## About The Pull Request

- This update fixes several issues with the Trek Chems patch, with how the reagents are handled on mobs and with code implementation.
- Adds synth-variants of the Trek chems that are weaker but can be used in a borg hypospray
- The ability to create medipens in the chem master based on a specified list of reagents, which currently includes Trek chems and advanced beneficial chems such as pen_acid, sal_acid, and oxandrolone.

## Why It's Good For The Game
Allows for more applications in chemistry by granting chemists the ability to transfer their advanced reagents into medipens within the chem master so that they can be used on mobs in hardsuits, etc.
Also allows for more EMT-esque methods of healing, as they can now stock up on medipens of various reagent-types for healing in the field.
Fixes issues that plague the Trek chems when people try to goof the system.
Let's mediborgs use Trek Chems!

## Changelog
:cl:
add: Medipen creation in chem master
add: Original Synthflesh back as synthflesh, uses different id and recipe. Patches and Medigel
add: charcoal bottle
add: Synth-versions of the Trek chems
edit: charcoal replacing multiver in chem smart fridge
edit: medipens now storable in chem smart fridge
tweak: styptic and silversulf patch volume from 10 to 15
fix: trek chems injection application, replaced set-lock
server: UI updated, run the asset builders
/:cl:

### CODE REVIEW

**Comment by Saliferous** [comment]
Re-opening because gitbot is annoying and closed it.

**Comment by TheSwain** [comment]
I think we just need the conflicts fixed and we can get going with merging?

**Comment by Saliferous** [comment]
> I think we just need the conflicts fixed and we can get going with merging?

I suppose that the ui changes can be ignored, as you will have to run the ui-updater on the host side for my changes to be made. The conflicts in chem_master are non-existent, it is just not liking the fact that I removed some empty space.

**Comment by Saliferous** [comment]
Resolved the conflicts, the only actual issue was with the ui, so I removed my changes to them and went with the default. You'll have to run the ui-updater on the host once this merge is done.

**Comment by TheSwain** [comment]
Alright I'm gonna be putting this guy in just as soon as I can

**Pull request merged**
