### PR TITLE
Infiltration gamemode.

### PR DESCRIPTION
**Pull request by EgorDinamit**
## About The Pull Request

This PR adds a new game-mode and antagonist - Syndicate Infiltrator.
Mechanically, it is the same old Traitor mode, but antagonists start in space with no real job on the station.
There is, in fact, a good advantage in it: They get a spacesuit, C4, Agent ID and Syndicate Headset(Non-Bowman type).

They also have 4 objectives, instead of 3, so we might see a bit more action(or 3 steal objectives, haha).
Instead of "Escape on the Shuttle" they get "Stay alive until the End"(IC reason, 'cuz they are not NT crew in **any** way, unlike traitors). They still might get Hijack or DAGD though.

## Why It's Good For The Game

Antag Variety was always a good thing.
Not only this, but they also have the best opportunity to cooperate with each other due to round-start headset and where they all spawn.

## Changelog
:cl: EgorDinamit
add: Added Infiltrator game-mode and Antagonist. Works almost the same as Traitor, but they start in space near the station and have to, guess what, INFILTRATE the station to complete their objectives!
config: Added "Infiltration" to game mode config and set it's chance to 4.
/:cl:

### CODE REVIEW

**Comment by glubtok** [comment]
Correct me if I'm making incorrect assumptions or imposing on your own creative process here please. Apologies in advance.

Calling it infiltrator implies a stealthy approach. The way I'm reading your description of it makes it sound like it's meant as a team-based stealth-ops type of game with traitor objectives, but implemented in a way that hinders the stealthy aspect of it. This is more like breach-and-go-loud based on the loadout and lack of crew ID/access. With regular nuke-ops, being a full syndicate agent is less disadvantageous because you only have the one team objective of getting the nuke disk. You can get in quickly and get out while going loud and still have a fighting chance. With infiltrator, you've got each person with their own 4 objectives to complete. You'd be hard-pressed to get them to cooperate if they don't all have the required cover and accesses from also being an NT crew member.

To illustrate, once this gamemode is around long enough for people to get familiar with it, you'd have a few problems:

- _If it's not a space suit that can be stored in a bag, you've got a very obvious identifier you'd need to dispose of at round start, lest a detective get your DNA from it._ 

- _Since you spawn around the exterior like a lone-op, a powergaming or knowledgeable AI would only have to incorporate a quick sweep to their round start routine around exterior cameras to determine if it's an infiltrator round (and identify a few). The extra motion alerts at round start from exterior motion cams could exacerbate this problem._

- _Assuming you're not on the crew manifest (given you said they have no real job at the start), knowledge of the round type from the above two points could easily blow your cover. All sec would have to do is put a discharged/paroled status on all crew members. Anyone without an icon or ID would then be target for searching._

- _You can't blend in with the crew and infiltrate if your ID is an agent ID. Trying to get a job at the HOP line to do so is out of the question, as handing them an agent ID for a job change will immediately add the chameleon button in the top left, alerting them to your role._

- _The syndicate headset is a dead giveaway. Syndicate encryption keys are cheap enough anyway via uplink. With knowledge of the round type, you'll have people rightclick>examining everyone._ 


Some ideas to make this better:

- _Start more from nuke ops round mechanics instead of traitor by having them spawn at the syndie base. This would throw off the round-start AI camera sweep timing and allow full team deployment via the nukie ship outside of camera range and in places without motion cams._

- _Add a custom round-start, temporary infiltrator hardsuit with an active function to "dematerialize" it or "bluespace it away", ideally used once you reach the station._

- _Include the infiltrators in the manifest as the job they rolled. This can be justified IC as "The syndicate has hacked personnel records and forged your cover identities ahead of time." This would include regular IDs with their set jobs' access on top of having an agent ID (Their legitimate departmental ID should be in their bag, with their agent ID spawning in their ID slot so they show up as unknown as they approach.)_

- _Spawn them implanted with an internal syndicate radio, a full chameleon set and an airlock card. Drop the C4 for stealth reasons. Remove the declaration of war mechanic and give them the standard 20tc to play with like a regular traitor._

**Comment by Drackzo** [comment]
Just some corrections, the space suit + helmet (unless they work differently from the regular traitor space suit + helmet)  are both normal sized items and fit in bags, they also fit in the box they come in so it'd be cool to add that to their starting inventory. Also the non bowman syndicate headset, if it's the one I'm thinking of, just looks like a regular headset upon examination.

I like the idea of spawning them in the syndie outpost but infiltrator shuttle control will be a major point of contention since for example someone might move it or call it out of z level when someone else might want to go back to it for heals etc, so maybe you'd have to make a different mode of transport for them to get to station and back or change the infiltrator to be remote controlled and encourage communication between the antags. 

Can infiltrators get the same steal objective? Multiple infiltrators fighting over the hypospray would undermine the teamwork aspect, though on the other hand you could argue that it's similar to "absorb another changeling" and should be part of the mode. Maybe, similar to ling, you could give them some team objectives and solo objectives?

**Comment by EgorDinamit** [comment]
I am working on it, but yeah, it won't be 100% team antag, you still can get as asassination objective on infiltrators as one.

**Comment by glubtok** [comment]
I removed my objectives suggestion while editing and forgot to put it back in. They should have separate steal objectives for sure. To promote teamwork however, they could have a shared kill list about 1/2 the size of the team or something.

For the shuttle contention issue, there really isn't a reason to call the ship back to the syndie z level outside of everyone greentexting. Stranding your infiltrators could be dealt with via core rule 2 or other added teamwork policy.

**Comment by Drackzo** [comment]
I'd use the shuttle to dispose of bodies or maybe move it to a more advantageous position for what I'm trying to accomplish, eg. above the armory if I need to steal the ablative trenchcoat. It's also really really powerful, the turrets shoot penetrator shots I believe. Not sure if infiltrators should have access to this level of firepower.

**Pull request merged**
