### PR TITLE
okay everyone give me a perception check

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request
New item for tator curators:

Bag of encounters - 8TC
Looks like a normal bag of dice, has no way to distinguish it from any other unless used. The bag can be rattled in-hand once to establish its owner. There are three dice inside, providing three scintillating random encounters; 1d4 wild bears, 1d6 feral carp, and the powerful Bee20. These can be rolled inhand or thrown.

## Why It's Good For The Game
Curator has 1 traitor item atm and it fucking sucks.

## Changelog
:cl:
add: Intelligence suggests the syndicate have begun equipping their more bookish agents with DnD-themed equipment. Nerds.
add: A new lawset has emerged, check your monster manual.
/:cl:

### CODE REVIEW

**Comment by CosmicPhoenix** [comment]
I play SS13 to get better at roleplaying in D&D. This removes the need for me to play D&D outside of SS13. Best change possible. 👌

**Comment by TheSwain** [comment]
Yo Mith - turns out you can do all this without altering ANY TG files at all, if you just make them as a new object with /obj/item/dice/ as the parent. Basically, put it all in dice_fulp.dm

/obj/item/dice/dnd   // Establish this as a new dice type
	var/dice_spawn = null //fulp
	var/owner = null //fulp

/obj/item/dice/dnd/diceroll(mob/user)   
	..()  // Do the base dice roll first.
	dicespawn(dice_spawn)   


...and so on, change everything that might be pointing to the wrong version of /obj/item/dice instead of /obj/item/dice/dnd, etc.

**Comment by ghost** [comment]
That would mean a lot of copypaste code since the specific dice types wouldnt be inheriting the vars from their non-traitor versions. I figured 4 lines in a /tg/ file would be better than 8 lines in a _fulp file per item.

That being said, it wont be a hard change. I'll do it tommorow.

**Comment by ghost** [comment]
Ite this should be kosher now

**Pull request merged**
