### PR TITLE
4 new Wing sprites for Mothpeople made by Papaporo

### PR DESCRIPTION
**Pull request by GuillaumePrata**
## About The Pull Request
Adds 4 new Wing sprites made by Papaporo and hopefully doesnt break anything... 
https://i.imgur.com/u5HOPSM.png
If there is anything I can do better, please tell.

## Why It's Good For The Game
Customization is good.

## Changelog
:cl: Guillaume Prata
add: 4 wing sprites so you can stand out in the lamp loving crowd easier.
code: Add some lines to 'sprite_accessories.dm'
/:cl:

### CODE REVIEW

**Comment by Paprito** [comment]
wee

**Comment by TheSwain** [comment]
Can anyone give this a test to see if it works as intended? I like cosmetic additions.

Only request: there's no need to add your code to an existing TG .dm file. You can create your own and add it to the Fulpstation folder, or create a new .dm with an appropriate name (such as sprite_accessories_FULP.dm) that contains only your additions.

**Comment by Samuuu3** [comment]
moff

**Comment by Samuuu3** [comment]
These work when i test merged them. He changed his code location so you should look over it again. @TheSwain

**Pull request closed without merging**
