### PR TITLE
[READY] General fix for Cybersun ship.

### PR DESCRIPTION
**Pull request by EgorDinamit**
## About The Pull Request

Closes #345 

Adds antag datum and update sql_ban_system: Now admins can check antagonists for cybersun ops and ban specifically from playing it, instead of all ghost roles.
Adds two new cyborg upgrade modules: First one simply adds syndicate faction to a borg it's used on, and the second one, changes its module to special version of medical.
Adds two new loot spawners: One for round gimmick, and another one for armory(replacing meta armory lootdrop).
Adds botany and kitchen crates, with respective contents.
Reduces amount of materials and stock parts.

## Why It's Good For The Game

forgottenship-1

Bugs aren't good for the game and having more content is always better.

## Changelog
:cl:
add: Cybersun ship now contains a disk for autolathe, that allows you to print two new cyborg upgrades, and random lootspawners, one for "gimmick", another for armory.
fix: Cybersun ship ruin contains right ammo type now.
fix: Cybersun captain now actually spawns with jumpsuit and ID.
admin: Added antag datum for cybersun operatives. Now you can use "Check antags" and see them here. Additionaly, updated sql_ban_system so you can ban players from playing this role.
/:cl:

### CODE REVIEW

**Comment by remove32** [comment]
did you test the ban panel to ensure it shows for this antag?

**Comment by EgorDinamit** [comment]
Gotta check it tommorow.

**Comment by EgorDinamit** [comment]
Everything is tested and working, you can merge it any time.

**Comment by ErwinSnowden** [comment]
no merge. we no maintain code.

**Pull request merged**
