### PR TITLE
Tgupdate - Big Lad

### PR DESCRIPTION
**Pull request by remove32**
## About The Pull Request
Pulling from TG master, INDISCRIMINATELY!

## Why It's Good For The Game
Chaos is my best friend

## Changelog
:cl:
code: MERGE FOR THE GIT GOD!
/:cl:

### CODE REVIEW

**Comment by glubtok** [comment]
hello darkness my old friend

**Comment by AlucardHellsingChapel** [comment]
Exofab can't print posi brains can't print implants can't print organs resource icons arent visible 
If you augment yourself and try to take any organ it dosent allow you even if someone else tries 
if you get upgraded organs before augmentation you can't be augmented
you cannot print best battery from quantum only bluespace one

**Comment by remove32** [comment]
> 
> 
> Exofab can't print posi brains can't print implants can't print organs resource icons arent visible
> If you augment yourself and try to take any organ it dosent allow you even if someone else tries
> if you get upgraded organs before augmentation you can't be augmented
> you cannot print best battery from quantum only bluespace one

can the normal sci fab print posibrains? if so then i dont care about that. implants are meant to be more of a medbay thing, same with organs. sorry you're expected to interact with others. battery issue, i'll fix that, and will look into the resource icon thing. as for the augmentation thing, not sure what's up there and if that's normal for TG. augmenting yourself definitely used to not be a thing as self-surgery wasn't a thing

**Comment by AlucardHellsingChapel** [comment]
> > Exofab can't print posi brains can't print implants can't print organs resource icons arent visible
> > If you augment yourself and try to take any organ it dosent allow you even if someone else tries
> > if you get upgraded organs before augmentation you can't be augmented
> > you cannot print best battery from quantum only bluespace one
> 
> can the normal sci fab print posibrains? if so then i dont care about that. implants are meant to be more of a medbay thing, same with organs. sorry you're expected to interact with others. battery issue, i'll fix that, and will look into the resource icon thing. as for the augmentation thing, not sure what's up there and if that's normal for TG. augmenting yourself definitely used to not be a thing as self-surgery wasn't a thing

if you get augmented in cybernetic parts you can do selfsurgery

**Pull request merged**
