### PR TITLE
T5 update 10/3/19

### PR DESCRIPTION
**Pull request by gonenoculer5**
Changelog
:cl:
Renames a T5 tech
Fixes a spelling error
Adds some neat new T5 features to motorized wheelchairs
C r o m c h
/:cl:

### CODE REVIEW

**Comment by AtlasRules** [comment]
crunch

**Comment by gonenoculer5** [comment]
https://trello.com/c/SjFABhM3/15-t5-stock-parts

Forgot to mention it also fixes the Quantum Cells spawning with 100% charge and changes the matter bin name

**Comment by TheSwain** [comment]
what are all those wheelchair changes?

also, notice how the way you added a T5 check changes an entire block of TG's code. that is a no-no.
it would change far less if it didn't check "**if(t5 < 30)**", but instead:


> **if(t5 >= 30)** 
>       *do all my T5 stuff here*
>      **return**    *so we end here*
> 
> TG stuff stays down here untouched

**Comment by TheSwain** [comment]
also, each time the wheelchair refreshes it's going to add the rating. you never reset the t5 back to 0 on refresh. very time refresh_parts() gets called, t5 will get bigger and bigger and bigger.

**Comment by gonenoculer5** [comment]
Wouldnt refresh_parts() only be called once?

**Comment by TheSwain** [comment]
That's hard to say. By nature of the way the proc is named, I would assume it gets called any time a part goes into or out of the wheelchair. Maybe I'm wrong, but it's best practice to reset the value first when using += unless the intent is unlimited growth.

**Comment by gonenoculer5** [comment]
Well in order to update a part of the wheelchair you would have to deconstruct it, so this is not an issue for us, since refresh_parts() is only called once. As for the stuff with the code block in wheelchair code I already explained why it needs to be the way it is, changing it further would require modifying that code block further. If we could I would like to get this merged if there are no other issues, thanks!

**Comment by TheSwain** [comment]
after reading through again, i think my point on the **if(t5 < 30)** thing stands. you can easily have it check the opposite, do your T5 code, and use RETURN to abort before continuing on with the core TG functionality. that way, the TG code isn't getting tabbed forward (and thus altered), leaving it untouched.

**Review by gonenoculer5 — COMMENTED** [review]
Works for me

**Pull request merged**
