### PR TITLE
Syndie Balloon Two: Golden Boogaloo

### PR DESCRIPTION
**Pull request by CosmicPhoenix**
## About The Pull Request
Adds in a new traitor item, the Golden Syndicate Balloon, which comes in a box of three costing 60 TC. Promotes cooperation between Syndies to be the ultimate badasses.

## Why It's Good For The Game
Allows Traitors to finally flex on others in squads of three wielding pure gold balloons.

## Changelog
:cl:
add: Operatives may notice a new item within their uplinks requiring cooperation between three operatives to acquire. ~_The Syndicate_
/:cl:

### CODE REVIEW

**Comment by TheSwain** [comment]
Is this guy ready to go? Fully tested and you know it works?

**Comment by CosmicPhoenix** [comment]
They're fully tested, working, and ready to be merged.

**Comment by TheSwain** [comment]
MERGED

**Comment by CosmicPhoenix** [comment]
**SWAIN MERGED THE PR!!!** :wee:

**Pull request merged**
