### PR TITLE
Electroadaptive Psuedocircuit Tweak

### PR DESCRIPTION
**Pull request by Surrealaser**
:cl:
tweak: Engiborg Electroadapative Psuedocircuit now recharges somewhat faster, consumes glass and metal to mint circuits and can interface with windoor assemblies.
:cl:

### CODE REVIEW

**Comment by ATH1909** [comment]
Have you considered PRing some of these changes upstream at /tg/? This PR looks like something that non-fulp servers would like to have as well, regardless of their RP levels, rules, etc.

**Comment by TheSwain** [comment]
> Have you considered PRing some of these changes upstream at /tg/? This PR looks like something that non-fulp servers would like to have as well, regardless of their RP levels, rules, etc.

I agree. @Surrealaser I like our server having better balance than TG, but small things with big impact like this might even serve us better being part of TG (so we never have to worry about merge conflicts, especially)

**Comment by Surrealaser** [comment]
@ATH1909 @TheSwain I refuse to deal with Orange and his clique.

**Comment by remove32** [comment]
that being said, @TheSwain  this worked last I tried and can probably be merged. willing to testmerge it on the test server if you want though

**Comment by gonenoculer5** [comment]
> @ATH1909 @TheSwain I refuse to deal with Orange and his clique.

Yeah I agree with surreal on this one id prefer to keep things local unless we have to port them upstream, because id rather not have my code ret-conned by orange man and his baffoons

**Pull request merged**
