### PR TITLE
Adds Soap to Mediborg

### PR DESCRIPTION
**Pull request by Surrealaser**
### About The Pull Request
Gives the mediborg soap so it can actually disinfect surfaces and help stop the spread of disease instead of having to spam chem to do so.

### Why It's Good For The Game
As a mediborg, you currently have two options:

1: Waste chem charge to clean medbay in a tedious way with droppers, beaker spilling and/or hygiene foam bombs.

2: Let Medbay become a festering, disease spewing nightmare of blood and puke.

This change essentially adds some QoL to the Medborg, making spot cleaning less cancerous, without giving the borg module a capability it doesn't already have, and without treading on the toes of the Janiborg who cleans far more efficiently.

### Changelog
🆑
add: Mediborgs can finally use soap to clean up disease bearing blood, puke and mucus.
/🆑

### CODE REVIEW

**Comment by CosmicPhoenix** [comment]
https://github.com/tgstation/tgstation/issues/46627 for the big /tg/ debate on this.

**Comment by Surrealaser** [comment]
@CosmicPhoenix Honestly, none of their arguments are compelling; it's not a debate so much as a circlejerk, with all due respect.

**Comment by Saliferous** [comment]
Why not just have janiborgs for that? I mean I understand keeping sterile environments but the mediborgs purpose is to heal with either chems or surgery, not to clean.

**Comment by Surrealaser** [comment]
@Saliferous The addition of soap is almost purely QoL. You can actually clean more efficiently with chem, and you are grossly less efficient at cleaning than the Janiborg (doubly so with Soap). This steps on the toes of the Janiborg about as much as janiborg's floor tiles step on the toes of Engiborgs.

**Comment by ghost** [comment]
@TheSwain I see absolutely no reason this shouldnt work. Codewise it's gucchi.

**Pull request closed without merging**
