### PR TITLE
Hulk Nerf

### PR DESCRIPTION
**Pull request by Surrealaser**
:cl:
tweak: Standard power version that lacks stun immunity and immunity to damage slowdown. There is a full power version granted by spells/wishgranter that is identical to its current state.
/:cl:

### CODE REVIEW

**Comment by Shadowtail117** [comment]
Looks good. Hopefully this will stop the hulktide once and for all.

**Comment by Surrealaser** [comment]
@Shadowtail117 you can still utilize hulk safely via multiple injectors and a supply of mutadone to reverse mutations, but it requires much more effort and preparation, and it's not something you can just go around with in perpetuity all the time now.

**Comment by Shadowtail117** [comment]
Well yeah, if you're careful about it. But this should stop the majority of people who just go unga bunga inject me and go away to break into the armory.

**Comment by ATH1909** [comment]
Bruh.

I can't wait for someone to beat the entire wishgranter away mission and choose "power" as their reward, only to die horribly a minute later because it gives them hulk. The same thing applies with the lavaland wishgranter, by the way.

I also can't wait for geneticist traitors to use their special DNA syringe gun traitor item to shoot people with hulk syringes, basically ensuring their death if they don't have mutadone on their person.

**Comment by ATH1909** [comment]
Just makes hulks valid (if they aren't already). I've almost never seen so-called "hulktides" be a problem/appear at all, mostly because almost no one actually stops by Genetics to pick up powers (especially now that it's tucked away in a corner of Science instead of being right by Cloning in Medbay).

**Comment by ATH1909** [comment]
Why not just remove wallbashing from hulks, or at least give it a cooldown (say, 30 seconds to a minute between wall bashes?)? Isn't that the problematic part of the mutation? People will/would still use it without the wallbashing (mm, stun immunity), but they wouldn't destroy nearly as many walls while doing so.

**Comment by AtlasRules** [comment]
nerfing it is good and all

but it doesn’t deserve to exist

pull the trigger and have strength give you the extra melee damage

**Comment by Surrealaser** [comment]
@ATH1909 Death by syringe can be done faster by other means, and without giving someone the ability to break walls, stun immunity, and the ability to kick your ass (and in the meanwhile, you can't benefit from it nearly as much passively). I don't think that it can be leveraged sub-optimally in an offensive capacity is a problem. As with the wish granter, meh. Total corner case, and if I really wanted, it would be easy enough to make a child version that didn't have maxed out instability (or just change the powers granted). There is also a certain poetic and fitting justice/irony to the wish granter's gift turning out to be ultimately harmful.

Also, Hulk has two major problems: wall breaking and total stun immunity. It's also obnoxious asf in terms of its effects on text, but that is more tolerable.

**Comment by ghost** [comment]
this is not how

**Comment by ATH1909** [comment]
> @ATH1909 Death by syringe can be done faster by other means, and without giving someone the ability to break walls, stun immunity, and the ability to kick your ass (and in the meanwhile, you can't benefit from it nearly as much passively). I don't think that it can be leveraged sub-optimally in an offensive capacity is a problem. As with the wish granter, meh. Total corner case, and if I really wanted, it would be easy enough to make a child version that didn't have maxed out instability (or just change the powers granted). There is also a certain poetic and fitting justice/irony to the wish granter's gift turning out to be ultimately harmful.
> 
> Also, Hulk has two major problems: wall breaking and total stun immunity. It's also obnoxious asf in terms of its effects on text, but that is more tolerable.

Yeah, but death syringes don't make your victim's corpse completely unrezzable.

**Comment by Shadowtail117** [comment]
Making people turn into hulks as a way of killing them seems fine with me. It adds another option for antag geneticists. And plus, it shouldn't be too hard for them to just head to chemistry and have them make some mutadone.

**Comment by Surrealaser** [comment]
@ATH1909 The effects of genetic instability are RNG; it won't always permagib you. Personally I don't mind adjusting the permakill outcomes such that a brain/head is left behind.

**Comment by Buzzardman2** [comment]
Maybe instead of instantly being 100% you could make it so it increases instability the longer you have it that way it builds up to 100%? It would add the nerf without being so harsh on it at the same time.

**Comment by ATH1909** [comment]
Also, keep in mind that if you choose to go the "multiple injectors+mutadone" route, you're gonna remove all of your other mutations every time you clear out hulk.

> @ATH1909 The effects of genetic instability are RNG; it won't always permagib you. Personally I don't mind adjusting the permakill outcomes such that a brain/head is left behind.

But then the possible effects of genetic overloading would be much less dangerous, wacky, and fun!

**Comment by Surrealaser** [comment]
@ATH1909 Yes, that's one of the intended downsides with using hulk.

Also I'm not a fan of permadeath mechanics unless there is a really, really good reason for them. Honestly as wackiness goes, something like the Bolt of Chaos effect would be better.

**Comment by Kokojos** [comment]
This is not a good solution for the problem we have. Hulk gives too many advantages, but this outright crits you after using it, even if you discover it accidentally. Preparing for hulk just gives more to powergamers to do, since they'll be the only ones using it.

Please think of another solution.

**Comment by ATH1909** [comment]
What if you made the hulk mutation give you an activatable ability that made you enter "hulk mode" (with all of the normal benefits), but only for a certain duration (or until you end it manually)? This duration could be reset by being hit by projectiles or damaged in melee, and when it runs out, you exit hulk mode, the activatable ability enters cooldown, and you take a large chunk of stamina damage (which could stun you if you already had stamina damage)?

On second thought, that nerf doesn't really address your issues with the hulk mutation. Then again, neither does this PR (if you go the mutadone microdosing and spare hulk mutators route), really.

Aren't hulks still slowed down by stamina damage? Is the immunity to stuns given by the hulk mutations really a problem if sec has access to lethals (they use 'em often enough on non-hulks...)? Even if a sec officer just has a disabler, can't they still slow a hulk down to a crawl (and disable their arms and legs) with stamina damage?

**Comment by ATH1909** [comment]
> This is not a good solution for the problem we have. Hulk gives too many advantages, but this outright crits you after using it, even if you discover it accidentally. Preparing for hulk just gives more to powergamers to do, since they'll be the only ones using it.
> 
> Please think of another solution.

To be fair, you can't "discover hulk accidentally" unless you're raiding an away mission or interacting with a wishgranter; hulk is a mutation that doesn't occur "naturally" and instead has to be created by combining the radioactive and strength mutations in a genetics console.

**Comment by ATH1909** [comment]
Also, this fucks over the "Mutate" spell that wizards have access to. A wizard who casts Mutate x5 after this PR is merged can now accidentally permakill themselves by using a spell as intended, no?

**Comment by Surrealaser** [comment]
@ATH1909 Complicating Hulk use, and making it require careful usage of both multiple injectors and mutadone along with additional prep significantly reduces its abusability and excessive value; it is no longer a nobrainer mega buff that requires no care or finesse to use whatsoever. Cycling mutadone and injectors and tracking your countdown timer under pressure from Security is not at all trivial.

**Comment by Surrealaser** [comment]
@Kokojos As ATH has stated, Hulk is a 100% deliberate mutation.

**Comment by ATH1909** [comment]
> @Kokojos As ATH has stated, Hulk is a 100% deliberate mutation.

... Unless you use a wishgranter or the like.

Also, Mutate x5 is still a problem.

**Comment by Surrealaser** [comment]
Per the latest PR:

Hulk now has two versions:

1: Standard power version that lacks stun immunity and immunity to damage slowdown.

2: Full power version that is identical to its current state.

**Comment by ATH1909** [comment]
> Per the latest PR:
> 
> Hulk now has two versions:
> 
> 1: Standard power version that lacks stun immunity and immunity to damage slowdown.
> 
> 2: Full power version that is identical to its current state.

Shouldn't the nerfed version be KEEPING the stun immunity/slowdown immunity but LOSING the abilty that lets assistants punch through random walls that is causing these "hulktide" complaints?

**Comment by Surrealaser** [comment]
@ATH1909 Discussed this with you on the Discord.

I'm fine with people using hulk smash situationally, as long as they can be immediately and easily detained/punished by Sec without having to go straight to defcon 5 and needing a Warden to distribute shotguns (who knowing the player base probably isn't even at the Brig, playing the role like SO with better access).

**Comment by remove32** [comment]
i'm really not sure this is the best way to handle this. my lack of experience with genetics is showing but it seems really harsh

**Comment by ATH1909** [comment]
> @ATH1909 Discussed this with you on the Discord.
> 
> I'm fine with people using hulk smash situationally, as long as they can be immediately and easily detained/punished by Sec without having to go straight to defcon 5 and needing a Warden to distribute shotguns (who knowing the player base probably isn't even at the Brig, playing the role like SO with better access).

You mean that - _gasp_  - sec officers currnently have to try to use something OTHER than disablers and stun batons to try to solve all of their problems? Oh, the horror! We can't have that, now, can we?

Also, you do realize that lesser hulks can still break out of cuffs near-instantly, right? They're gonna have to crit or mutadone lesser hulks anyway.

**Comment by Surrealaser** [comment]
@ATH1909 Fixing cuffs is easy enough; I will probably do that tonight or tomorrow as needed. And letting Sec use disablers over shotguns they need to break out of the armory, and letting secborgs actually be able to handle Hulks is vastly preferable.

Going to be honest, thus far you sound like a powergamer trying to prevent one of his broken favourites from being brought to sanity.

**Comment by ATH1909** [comment]
> @ATH1909 Fixing cuffs is easy enough; I will probably do that tonight or tomorrow as needed. And letting Sec use disablers over shotguns they need to break out of the armory, and letting secborgs actually be able to handle Hulks is vastly preferable.
> 
> Going to be honest, thus far you sound like a powergamer trying to prevent one of his broken favourites from being brought to sanity.

I literally main nonhumans. The only times I ever start a round as a human are when I'm forced to due to the role I've chosen (RD, for example), and even then, I've only ever injected myself with hulk (as a human)... maybe once? Ever? And I definitely haven't ever hulked myself on fulpstation before (aside from using the lavaland wishgranter that one time, but I was a podperson then).

**Comment by Surrealaser** [comment]
@ATH1909 As stated in discord, the core of this problem is you have an easily mass-produced powerful perma buff that forces immediate lethal escalation vs people misbehaving and at a minimum strongly encourages Chemist valid hunting. Removing the arbitrary stun immunity, that to be honest, never made any sense in the first place (unlike the super strength), and allowing Sec Borgs and disablers/batons to actually work against Hulks is vastly preferable to the alternative of immediate lethal escalation (assuming we have a Warden doing his job in a timely fashion to begin with) against Hulk greentiders, which means either Sec is getting genocided, or the Hulks are. Bad.

**Comment by Misdoubtful** [comment]
This certainly seems confused to me and I'm not sure what the exact vision is here. 

Let alone the balance side of things, with hulks current 'issues'. 

The current approach being:

"Hulk now has two versions:
1: Standard power version that lacks stun immunity and immunity to damage slowdown.
2: Full power version that is identical to its current state."

People's biggest issue with hulk is that it is used to cause widespread station damage, I.E. breaking down doors, walls, and breaking other machinery. This is, more or less - a rules issue and enforcement problem. Removing stun and slowdown does not address this problem however. 

It keeps the issue that people have with 'hulktiders', while removing some benefits of hulk that make it worthwhile to use or provide to others. 

If Hulk were to exist solely for increased damage and breaking things - would that not incentivize using it solely for that reason?

At that point I would rather see Hulk commented out of the code altogether...

**Comment by Surrealaser** [comment]
@Misdoubtful There is no confusion.

The problem is cumulatively the ability to cause a lot of collateral damage, AND the relative inability of Sec to quickly and easily stop greentide.

I chose to remove the stun immunity for two reasons:

#1: Strength buffs make sense for the hulk mutation, stun and slowdown immunity do not.
#2: As stated previously, removing stun and slowdown immunity makes detaining and punishing hulks by sec easy, and moreover, allows secborgs to actually deal with them. It also doesn't require immediately escalating to lethals, or encouraging chemistry valid hunting, and taking players out of the round permanently.

Personally I don't mind deleting the hulk mutation from being attainable via genetics entirely.

**Pull request closed without merging**
