### PR TITLE
Firing Pins for Mech Weapons

### PR DESCRIPTION
**Pull request by Surrealaser**
## About The Pull Request

Mech weapons now need firing pins installed for them to work.  

To install a firing pin on a mech weapon, simply use the pin on it while it doesn't have one installed. To remove a pin, use a screwdriver on the weapon; this will destroy the pin.

## Why It's Good For The Game

Puts sane limits on the most powerful weapons in the game in line with their less powerful, but currently more restricted and secure hand-held weapons.

## Changelog
:cl:
add: Mech weapons now require firing pins in order to use. To install a firing pin on a mech weapon, simply use the pin on it while it doesn't have one installed. To remove a pin, use a screwdriver on the weapon; this will destroy the pin.
/:cl:

### CODE REVIEW

**Comment by SynnGraffkin** [comment]
Does this effect nuke op mechs?

**Comment by Surrealaser** [comment]
@SynnGraffkin No, they have pre-installed pins.

**Comment by TheSwain** [comment]
would it be easier to create the starting pin like this:

```
/obj/item/mecha_parts/mecha_equipment/weapon
	var/obj/item/firing_pin/pin //standard firing pin for most guns
	var/initial_firing_pin = /obj/item/firing_pin //standard firing pin for most guns //If it is unlocked by default, this is the firing pin type the weapon uses
```

**Comment by Surrealaser** [comment]
> would it be easier to create the starting pin like this:
> 
> ```
> /obj/item/mecha_parts/mecha_equipment/weapon
> 	var/obj/item/firing_pin/pin //standard firing pin for most guns
> 	var/initial_firing_pin = /obj/item/firing_pin //standard firing pin for most guns //If it is unlocked by default, this is the firing pin type the weapon uses
> ```

I wouldn't think so, mainly because weapons with included pins are the exception rather than the rule.

**Comment by remove32** [comment]
seems like this works fine. 
i agree that pins-in are the exception and should be handled when necessary rather than other way round

is it intended that the 217-D Heavy Plasma Cutter be printed with the pin in?

**Comment by Buzzardman2** [comment]
This would help a lot in preventing robotics from using weaponized mechs for themselves.

**Comment by Surrealaser** [comment]
@remove32 Plasma cutter is really more of a tool that can be used as a weapon.

**Pull request merged**
