### PR TITLE
Terragov

### PR DESCRIPTION
**Pull request by John-Dang**
## About The Pull Request
This is a complete rework of the Ashwalker Village, a whole new Necropolis! The temple has been moved to the center of the village, the clinic has been moved and reworked to be a shaman's hut, with makeshift surgery tools, mourning poultice and aloe. Longhouse has been added with small dining table, dirty mattresses and chests with 4 guard/hunter loadouts, 1 architect loadout, and 1 farmer loadout. Village Chief's home has been added, with a throne and a couple minor trophies for the chief to hold meetings or hearings with villagers/outsiders. Across from the chief's home is a new shop building, which could be used internally or with those passing by. The farm has also been reworked, with more plots, seeds for bufo, cotton, bamboo, aloe, towercap and glowcap. The entire area has storm protection as it is all now "ashwalker" area. The bodies are replaced with charred skeletons.
image

## Why It's Good For The Game
Reworks the Necropolis to be more of a village, gives more RP opportunity and visual distinction between villagers, gives them more to interact with and more to do. Also, removes the Malf AI disk and syndicate toolbox from the village area.

## Changelog
:cl:
add: Added new things
add: Added more things
del: Removed old things
tweak: tweaked a few things
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

### CODE REVIEW

**Comment by Nobelium-XVIII** [comment]
5,214 commits...

**Comment by Gurkenglas** [comment]
No more combat software upgrade if an expedition defeats or befriends the Ashwalkers? Why :(?

**Comment by JohnFulpWillard** [comment]
This man has just did the TGU for us AND is giving us new content? Brilliant! Swain, hire this man.

**Comment by ATH1909** [comment]
"Also, removes the Malf AI disk and syndicate toolbox from the village area."
but why tho

**Comment by EgorDinamit** [comment]
Dude, you fucked up.

**Comment by remove32** [comment]
not maintaining theswain's version of the repo anymore. i should archive this repo actually

**Comment by wraith-54321** [comment]
I mean, malf AI disk mayyyyybe, but why in the world the syndie toolbox

**Pull request closed without merging**
