### PR TITLE
Secborg Patch - URGENT PRIORITY

### PR DESCRIPTION
**Pull request by Surrealaser**
Fixes issues; improves organization of secborg update file.

### CODE REVIEW

**Comment by Surrealaser** [comment]
@TheSwain Definitely merge this before making the secborg update stuff live.

**Comment by ATH1909** [comment]
By the way, are you sure that "GLOB.security_level _<_ SEC_LEVEL_RED" shouldn't be "GLOB.security_level _<=_ SEC_LEVEL_RED"?

**Comment by Surrealaser** [comment]
@ATH1909 when the sec level is red or greater, you are allowed to swap to kill mode; if it's less, you're not.

```//Security levels
#define SEC_LEVEL_GREEN	0
#define SEC_LEVEL_BLUE	1
#define SEC_LEVEL_RED	2 (if less than this, you cannot shoot on kill mode without being emagged)
#define SEC_LEVEL_DELTA	3```

**Comment by ATH1909** [comment]
> @ATH1909 when the sec level is red or greater, you are allowed to swap to kill mode; if it's less, you're not.
> 
> ```
> #define SEC_LEVEL_GREEN	0
> #define SEC_LEVEL_BLUE	1
> #define SEC_LEVEL_RED	2 (if less than this, you cannot shoot on kill mode without being emagged)
> #define SEC_LEVEL_DELTA	3```
> ```

Oh, it's when you CAN'T shoot with it, I get it now.

**Comment by TheSwain** [comment]
@Surrealaser oops i added the sec improvement already. should i hold off on this? i can do it asap if we're okay.

**Comment by Surrealaser** [comment]
@TheSwain This addresses outstanding bugs with the secborg; their integrated egun cannot fire without it; this needs to be merged ASAP.

**Pull request merged**
