### PR TITLE
Security/Medical/Engineering Protolathes/Techfabs Now Require Access

### PR DESCRIPTION
**Pull request by Surrealaser**
:cl:
tweak: Security, Medical and Engineering protolathes and tech fabricators now require appropriate access.
/:cl:

### CODE REVIEW

**Comment by ATH1909** [comment]
ehhhhhhhhhhhhhhh

I _like_ being able to print stock parts for my department if the scientists are all too lazy/dead to do it for me, though. This also locks yet more traitor gimmicks behind getting AA/buying a budget emag.

Was the service protolathe left out of this list intentionally?

Personally, I'd recommend adding a wire to the hacking menus of protolathes and circuit fabricators that'd disable their access requirements if cut or something, just in case someone urgently needs to use them.

**Comment by Surrealaser** [comment]
@ATH1909 You still can. Science protolathe is not locked.

**Comment by ATH1909** [comment]
So, er, what made you decide to PR this change? How will it improve the game?

**Comment by Surrealaser** [comment]
@ATH1909 Mainly the increased importance/value of the security protolathe and what it can make.

Locking the others at the same time in favour of their proper users seemed like a good idea.

**Pull request closed without merging**
