### PR TITLE
Makes sleepy pen available to nuclear and clown operative uplinks.

### PR DESCRIPTION
**Pull request by glubtok**
## About The Pull Request
See title. 

## Why It's Good For The Game
Stealth ops has always been a viable thing, though we haven't seen much of it recently, Having a silent hypospray-like tool to knock a person out (and heavily synergize with the poison kit) is kind of a no-brainer. I don't see why something like this was ever barred from nukies in the first place. Given how often we end up with war being declared on these rounds, stealthier gear choices should hopefully bring more variety to nukies' approach.

## Changelog
:cl:
tweak: Made sleepy pen available to ops
/:cl:

(Apologies for the cluttered commit history. I realized guill was handling the romerol thing so I reverted that and misclicked shit D:)

### CODE REVIEW

**Comment by ATH1909** [comment]
image
https://www.youtube.com/watch?v=rLhzbjaaOPA

(try not to PR from/write your code in your master branch, as doing so usually leads to having a bad time when trying to make future PRs)

**Comment by ATH1909** [comment]
EDIT: Actually, I'm gonna take the time to confirm the accuracy of what I was gonna say here.

EDIT EDIT: Yeah, sleepypens were much stronger back when they were first removed from the op uplink, this PR is probably fine.

**Comment by glubtok** [comment]
Ah, I see what everyone else is doing. Basically a new branch for each proposed change/related sets of changes? 

I can see that if I want to make another PR in the meantime, all of them will contain the sleepypen changes as well. Still new to this xD.

Either way, I'm gonna nuke and re-fork my repo if/when this gets merged.

**Comment by remove32** [comment]
fix the conflict and i'll merge this :)

**Comment by glubtok** [comment]
It seems like it was getting pissy over white space smh. fixed

**Comment by glubtok** [comment]
honk

**Pull request merged**
