### PR TITLE
Increased AI Upload Security

### PR DESCRIPTION
**Pull request by Surrealaser**
:cl:
add: You now require an ID with AI Upload access to use the Borg and AI upload consoles.
add: Emags can break the security protocols on these consoles, allowing them to be usable by anyone but they will require 60 seconds to do so, and this will alert Security over the security channel with the location of the hacked console.
tweak: Syndicate hacked lawset board uplink item can hack upload consoles like an emag.
/:cl:

### CODE REVIEW

**Comment by ATH1909** [comment]
Suggestion: Allowed hacked upload boards (the ones you can purchase as a traitor for 7 TC, IIRC) to also initiate that "AI upload emagging" process.

**Comment by ATH1909** [comment]
Also, "allowing them to be **usable**" in that changelog should instead be " allowing them to be **used**".

**Comment by Surrealaser** [comment]
> Suggestion: Allowed hacked upload boards (the ones you can purchase as a traitor for 7 TC, IIRC) to also initiate that "AI upload emagging" process.

What do you mean exactly? Are you talking about law boards? I'll consider potentially reducing their cost in light of needing an emag to circumvent security (though let's face it, you will usually want to pair it with an emag anyways), but I don't like the idea of snowflaking hacking behaviour for them.

**Comment by ATH1909** [comment]
> > Suggestion: Allowed hacked upload boards (the ones you can purchase as a traitor for 7 TC, IIRC) to also initiate that "AI upload emagging" process.
> 
> What do you mean exactly? Are you talking about law boards? I'll consider potentially reducing their cost in light of needing an emag to circumvent security, but I don't like the idea of snowflaking hacking behaviour for them.

What I mean was that you should just make it so that using an emag OR using a hacked law board on an AI upload console can start that countdown to bring it to an emagged state.

**Comment by Surrealaser** [comment]
@ATH1909 yeah that would have them run an emag_act on a snowflake basis. I'm not sure if I like it. I think probably prefer decreasing the TC cost more than anything.

**Comment by ATH1909** [comment]
> @ATH1909 yeah that would have them run an emag_act on a snowflake basis. I'm not sure if I like it. I think probably prefer decreasing the TC cost more than anything.

Haven't you yourself crusaded against emag bloat and about how every traitor is pretty much obligated to buy an emag?

**Comment by Surrealaser** [comment]
@ATH1909 I'm basically trying to determine which is the lesser evil.

Also the board normally costs 9 TC.

**Comment by Surrealaser** [comment]
Alright, I've made it so the syndicate hacked lawset board from the uplink can now hack upload consoles as per an emag.

**Comment by Surrealaser** [comment]
Resolved conflicts.

**Pull request closed without merging**
