### PR TITLE
[READY] Bio-Sphere space ruin.

### PR DESCRIPTION
**Pull request by EgorDinamit**
## About The Pull Request

Adds a new space ruin into the game.

## Why It's Good For The Game

More space content.
smallsphere-1

## Changelog
:cl:
add: Added new space ruin - Bio-Sphere.

/:cl:

### CODE REVIEW

**Comment by remove32** [comment]
What are the red Xs with Ss next to them on the outside of the ruin? dead syndicate?

**Comment by EgorDinamit** [comment]
It's guardsmen' corpses specific to this ruins

**Comment by MaltVinegar** [comment]
You're making me want to explore space again

**Comment by EgorDinamit** [comment]
That's exactly what I am trying to accomplish.

**Pull request closed without merging**
