### PR TITLE
[READY] Hulk Nerf

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

This PR nerfs the Hulk mutation's stun immunity, adds new negative traits and changes variables to further nerf the Hulk.

- Stun immunity was reduced to Stun Resistance
- Instability was changed to 99, meaning any other mutation added to the player will harm them.
- Health requirement was bumped to 75, no hulking when badly hurt.
- Clumsy trait was added, meaning manipulation of items is harder and the player may fall over (Hulks lose some fine motor skill, right?).
- Dumb trait was added. 

## Why It's Good For The Game

This was a required nerf due to the rampant use of this mutation for tiding. By adding these nerfs, the mutation will be less appealing to tiders. This does not mean this mutation is useless however, you still have the strength to punch through doors and such, but it should dissuade some tiders from using it as an easy way to destroy the station. 

Security also had problem with dealing with Hulks since they could not be stunned. While yes, they could shoot the hulk with mutadone, the chemical isnt always available and nor are the guns to shoot them. Chemistry might be dead because hulks ravaged them. By reducing from immunity to resistance, Hulks should be more manageable for Security.

## Changelog
:cl:
add: Nerfed hulk variables.
add: Added negative traits.
/:cl:

### CODE REVIEW

**Comment by ATH1909** [comment]
image

image

**Comment by ATH1909** [comment]
> Stun immunity was reduced to Stun Resistance

This would normally be awful, as stun resistance doesn't reduce the stamina damage from batons (meaning that they still two-shot you and slow you down), but hulks ignore damage slowdown, so I suppose this can sort of be useful for running away from a sec officer who's using a baton instead of, say, a flash.

This change does absolutely kill the viability of using the hulk mutation against xenos, as the stun resistance trait does jack shit against anything that's not a baton. This also makes the Mutate wizard spell even worse (somehow).

> Health requirement was bumped to 75, no hulking when badly hurt.

25 damage is not "badly hurt". That's not even enough damage to cause damage slowdown.

> Clumsy trait was added, meaning manipulation of items is harder and the player may fall over (Hulks lose some fine motor skill, right?).

Hulks already can't use certain items, such as double bladed energy swords (and guns), due to their fat fingers. This is unnecessary, IMO (you're already making people give up guns; why are you making them give up cuffs as well?).

> Dumb trait was added.

Isn't that already kind of represented by the screaming that hulks do?

> Instability was changed to 99, meaning any other mutation added to the player will harm them.

https://www.youtube.com/watch?v=UcZzlPGnKdU

**Comment by ATH1909** [comment]
If all this PR did was replace the stun immunity of hulks with stun resistance (which really should be named "baton resistance"), I could maybe support it, but the pile of other nerfs (ESPECIALLY the instability increase) go(es) way too far. This is a 👎 from me.

**Comment by optimumtact** [comment]
ath ath tried to get a lynch mob from /tg/ to post on this pr

**Comment by Samuuu3** [comment]
Ath has plenty of people against this in Fulp I don't see why he needs to do that. Stinky

**Comment by PapaSejd** [comment]
Hey people wanted there to be NO stun resistance or immunity at all, but I thought that would be too much of a nerf. The Hulk's strength is all still there, and while its easier to lose in one now you can still beat the shit out of whoever is infront of you.

**Comment by ghost** [comment]
> If all this PR did was replace the stun immunity of hulks with stun resistance (which really should be named "baton resistance"), I could maybe support it, but the pile of other nerfs (ESPECIALLY the instability increase) go(es) way too far. This is a 👎 from me.

If I see that other people share this sentiment ill change it to just stun resistance.

**Comment by GoldenAlpharex** [comment]
We really need this in our lives. Hulks add nothing good to the game, is just a pain in the butt, so seeing it nerfed is any Research Director's dream. I wholeheartedly support this PR.

**Comment by ATH1909** [comment]
> ath ath tried to get a lynch mob from /tg/ to post on this pr

I posted a link to this PR on the /tg/station discord server, but I didn't tell people to downvote it, post angry comments on it, or the like (which, as you've probably noticed, they haven't done).

**Comment by ErwinSnowden** [comment]
This is not a code issue, this is a rules issue, people who abuse hulk should be geneticist banned. A good way of balancing hulk would be to make it considerably harder to get rather than to make it completely useless beyond making a ton of breaches and die at the threat of two hits by a toolbox because you instantly lose your hulk status. 

This proposal really removes the fun from a feature instead of thinking about ways to rebalance it. Locking many mutations behind upgrades for genetics would actually make it take considerable player co-operation, make it more noticeable for individuals who don't like hulks to see and take action and overall increase roleplay fluidity. 

It really seems like too much, considering it's primarily supposed to be a fun antagonist gimmick.

**Comment by GoldenAlpharex** [comment]
> This is not a code issue, this is a rules issue, people who abuse hulk should be geneticist banned. A good way of balancing hulk would be to make it considerably harder to get rather than to make it completely useless beyond making a ton of breaches and die at the threat of two hits by a toolbox because you instantly lose your hulk status.
The problem with that is that people don't understand that it's against the rule, and get bwoinked about it all the time.  Making it harder to get is an idea, but I think that a nerf is still necessary for this thing, since it's just way too strong as-is.

> This proposal really removes the fun from a feature instead of thinking about ways to rebalance it. Locking many mutations behind upgrades for genetics would actually make it take considerable player co-operation, make it more noticeable for individuals who don't like hulks to see and take action and overall increase roleplay fluidity.
> 
Well, that sounds like a good idea on paper, but that would still mean that people would still be able to get it within the first thirty minutes of a round, which isn't much different than what it is right now. It would also entail a complete rework of Genetics, which are on their own pretty okay as-is, I would say, aside the minor hiccup that is the Hulk mutation.

> It really seems like too much, considering it's primarily supposed to be a fun antagonist gimmick.
That's it. You just nailed it. It's supposed to be a _fun antagonist gimmick_. Not something your everyday Joe should be able to get his hands on and then give the Reinforced Chromosome to, and be simple unable to be stop, while he's still an antag, and just go "AAAAAH HULK ANGRY, HULK GO SMASH!!!"
If it was really an antagonist gimmick, then lock it behind Telecrystals or something, because I'll be honest, in my near 300 hours of gameplay, 41 hours of which are as a Research Director, I can tell you this one thing, that Hulks I've seen most often than not just inject themselves and go "HULK ANGRY, HULK SMASH!!!" and basically just go self-antag all over the department, which is just the most annoying thing ever. There's no way to stop them currently, aside from shooting them with a syringe gun with mutadone syringes in them, which is somewhat difficult to obtain for a RD, especially with Mutadone syringes, before any damage is done. I've never, ever, seen an Antag Hulk, because it's just not good enough to be an Antag as. It's just an easy trap to get new people bwoinked, which it shouldn't be. If you want it to be an antagonist gimmick, then lock it behind being an antagonist.

**Comment by ATH1909** [comment]
You do know that you can just shotgun (or kite with a laser gun) hulks who are being shitters, right? Unless Fulp changed the policy on this, hulks are valid to be lethal'd into crit if they act up.

**Comment by GoldenAlpharex** [comment]
> You do know that you can just shotgun (or kite with a laser gun) hulks who are being shitters, right? Unless Fulp changed the policy on this, hulks are valid to be lethal'd into crit if they act up.

Oh, yeah, I totally know that, but it's just that 1. The Research Director doesn't have access to such weapons to deal with them, it would have to be security, which is honestly an unneeded additional thing for Security to have to deal with.
2. I just think that it will benefit us in the way that Hulk Tiding will be MUCH more rare once this comes into effect, or will be able to be stopped much earlier. I've seen my cool rounds as a RD being ruined because of Hulks destroying a lot of walls and airlocks in my department and then Engineering being too busy with the SM or a bombed Medbay to deal with it, so people just come in and out, stealing stuff and becoming Hulks themselves. 
I'd genuinely want to know all your "pro-Hulk" reasons, just to see if I'm only biased by how much I've been cucked by them as a RD in my time, because honestly, so far, only reason to keep Hulk the way it is is that "It's a fun Antag gimmick", which I've personally never, ever seen in action, and by that I mean I've never seen someone that's actually an antag being a Hulk.

**Comment by ATH1909** [comment]
> > You do know that you can just shotgun (or kite with a laser gun) hulks who are being shitters, right? Unless Fulp changed the policy on this, hulks are valid to be lethal'd into crit if they act up.
> 
> Oh, yeah, I totally know that, but it's just that 1. The Research Director doesn't have access to such weapons to deal with them, it would have to be security, which is honestly an unneeded additional thing for Security to have to deal with.
> 2. I just think that it will benefit us in the way that Hulk Tiding will be MUCH more rare once this comes into effect, or will be able to be stopped much earlier. I've seen my cool rounds as a RD being ruined because of Hulks destroying a lot of walls and airlocks in my department and then Engineering being too busy with the SM or a bombed Medbay to deal with it, so people just come in and out, stealing stuff and becoming Hulks themselves.
> I'd genuinely want to know all your "pro-Hulk" reasons, just to see if I'm only biased by how much I've been cucked by them as a RD in my time, because honestly, so far, only reason to keep Hulk the way it is is that "It's a fun Antag gimmick", which I've personally never, ever seen in action, and by that I mean I've never seen someone that's actually an antag being a Hulk.

There's a difference between nerfing hulks to make them easier to deal with and nerfing them so badly that they'll never see ANY use (except by people who mistakenly believe that they're still at their old power level/the power level they're at on other servers). Replacing the stun immunity with baton resistance would be enough, but making hulk incompatible with other mutations (including utility mutations like x-ray and thermal vision) and able to be disabled in 3 bonks of a goddamn POTTED PLANT is going way too far.

IMO, a better solution would be to either remove the wall smashing from the version of hulk that you can get from genetics (since hulks smashing holes in your department(s) seems to be your biggest gripe with them) OR giving hulks a giant message telling them that being a hulk doesn't give them a license to self-antag when they receive the mutation, like the one that people with Reality Dissociation Syndrome get.

**Comment by ATH1909** [comment]
You could also make it so that a message (that includes the location of the console) be stated over sci comms whenever a hulk mutator is printed.

Also, you do know that RDs have basic engineering access, right? You can go over to an engineering vendor and buy an RCD (or print a fully-loaded RCD from an engilathe) that you can use to fix the holes in your department yourself (perhaps after heading over to Sec to receive a hybrid energy gun that you can use to easily kite hulks into crit).

**Comment by GoldenAlpharex** [comment]
> You could also make it so that a message (that includes the location of the console) be stated over sci comms whenever a hulk mutator is printed.
> 
> Also, you do know that RDs have basic engineering access, right? You can go over to an engineering vendor and buy an RCD (or print a fully-loaded RCD from an engilathe) that you can use to fix the holes in your department yourself (perhaps after heading over to Sec to receive a hybrid energy gun that you can use to easily kite hulks into crit).

I know, but a RD has already other things to deal with than doing the Engineer's job. While I do agree that there's other ways to nerf the Hulks, I just really want a nerf to happen.

**Pull request closed without merging**
