### PR TITLE
Cryosting Now Has a Cooldown

### PR DESCRIPTION
**Pull request by Surrealaser**
### About The Pull Request
Changeling cryosting now has a 10 second cooldown.

As partial compensation, the frost oil amount injected has been increased to 40U; this should be just enough to put someone naked for the entire metabolization of the chemical into crit assuming they don't get treatment for burn damage.

### Why It's Good For The Game

Prevents the changeling from dumping ultra-lethal fucktons of frost oil into someone's bloodstream in an instant even while restrained, proned, etc... 40U per injection is extremely powerful. No more Sting of the Northstar.

### Changelog
🆑
add: Changeling cryosting now has a 10 second cooldown. Frost Oil amount injected increased from 30U to 40U.
/🆑

### CODE REVIEW

**Comment by ghost** [comment]
Yeah I'm not a fan of this.

**Comment by Surrealaser** [comment]
@Mithrandalf Any specific reasons? It's utterly insane how changelings can dole out over 100U Fist of the Northstar style in effectively an instant even through disables and restraints. Even with purge chems you're not surviving that unless you get to a source of heat, and even if you do, you'll be hugging it for a very long time, or drinking the station's entire supply of coffee.

It's an utterly broken ability as is.

**Comment by Surrealaser** [comment]
Closing in favour of a nerf that removes the stealth component of cryosting after discussion with Mithrandalf.

**Comment by BLUREMOTE** [comment]
This does genuinly sound a lot better than the stealth removal.
You can still make a sneaky delayed strike bit your target is more likely to survive without the stacking

**Comment by Saliferous** [comment]
I'm perfectly fine with either, although I feel as though the non-stealthy is better.

**Comment by TheSwain** [comment]
Commented on the other PR, I prefer a cooldown over removing stealth. Since there seems to be a pretty contrasting disparity in opinions over this, maybe we should discuss it as a group before putting more work into either one of these solutions.

**Comment by ghost** [comment]
Codewise it seems fine @TheSwain

**Comment by Surrealaser** [comment]
I think a good compromise would be to increase the frost oil inject amount to 40U or 45U with the 10 second cooldown. This is a lethal amount without treatment, getting you to crit and slow suffocation, even if you're naked for the entire duration of the Frost Oil metabolization.

**Pull request closed without merging**
