### PR TITLE
Just saiyan armor

### PR DESCRIPTION
**Pull request by TheTeenyTiny**
## About The Pull Request
Adds the costume, siayan armor from DBZ

## Why It's Good For The Game
It matches the medhud 

## Changelog
:cl:
add: sprite for armor
add: code for armor
code: changed some code in autodrobe
/:cl:

### CODE REVIEW

**Comment by TheSwain** [comment]
Hi! i see there is a change to mob.dmi in here - we can't overwrite TG's .dmi files, because they'll just get steamrolled as soon as TG decides to change the file themselves. All new sprites need to go into new, unique .dmi files.

**Comment by TheTeenyTiny** [comment]
So the mob.dmi just houses a goof I was making, so it's fine for it to get overwritten unless you want me to take it out (just in case you didn't see the ping, please don't hurt me lol)

**Comment by TheSwain** [comment]
Yea see if you can revert mob.dmi to being unchanged and push that boy again. After that it's an easy merge.

**Comment by TheTeenyTiny** [comment]
I did it (I think)

**Comment by TheSwain** [comment]
mob.dmi still showing under Files Changed tab

**Pull request merged**
