### PR TITLE
Detective can now get sec gear

### PR DESCRIPTION
**Pull request by BLUREMOTE**
## About The Pull Request

This is more of a test than anything, to help with how often sec is left alone with someone that cant really do anything.
This add security access to the detective (aka sec locker room (or the locker since some map allow the detective in the room but not to the locker), sec offices, timer on prison)
Im aware this sound a lot like Sec Officer+ but like, the poor lad cant do shit properly if he is alone.

## Why It's Good For The Game

Usually in low pop and without a hos or hop, the detective is way less ready to non lethally remove someone. This could help a bit to fix that.

## Changelog
:cl:
Detective now as clearance to access regular sec gear to fill in missing officers.
/:cl:

### CODE REVIEW

**Comment by TheSwain** [comment]
I need to consider this with the admins. Since this is a Medium RP server now, giving players a job with limits is not a bad thing. If players wanted to play security, they'd pick security. Plus HoP/Cap can always grant access.

**Comment by BLUREMOTE** [comment]
> I need to consider this with the admins. Since this is a Medium RP server now, giving players a job with limits is not a bad thing. If players wanted to play security, they'd pick security. Plus HoP/Cap can always grant access.

I did mention the moment where cap/hos/hop are not present, so if thats the case, detective is kinda cucked and the antag gonna go "its free real estate"

**Comment by TheSwain** [comment]
You're saying detective should have sec access at roundstart if no sec spawned, but this change gives him access all the time. He can now do sec's job for them when there ARE sec on the station, too, which we do not want.

The right way to make this change would be to upgrade detective's access at roundstart if no sec spawned, the same way sec gets department access if they're assigned there.

**Comment by BLUREMOTE** [comment]
> You're saying detective should have sec access at roundstart if no sec spawned, but this change gives him access all the time. He can now do sec's job for them when there ARE sec on the station, too, which we do not want.
> 
> The right way to make this change would be to upgrade detective's access at roundstart if no sec spawned, the same way sec gets department access if they're assigned there.

Thats indeed one of the problems...
I havent found the part of the code that dictacte what is a skeleton crew or not and how much bonus access you got.

**Pull request closed without merging**
