### PR TITLE
Minebot Upgrades and Additions

### PR DESCRIPTION
**Pull request by GoldenAlpharex**
## About The Pull Request
The Minebot has received some love it deserved. First of all, according to Nanotransen's new safety regulations, Minebots are now equipped by default with an ash-proof chassis. This only makes sense for a bot that was made to mine on a planet where ash storms are frequent. As a result of that new chassis, the Minebots are now also near-immune to high-temperatures. Alongside the new chassis, the Minebots are also equipped with an internal GPS signal emitter, which allows anyone with a GPS to be able to find them at any time, without giving the Minebot any access to use said GPS on their own, as Nanotransen doesn't want a Minebot uprising. Then, a whole new selection of upgrades are now available for Minebot owners that don't know what to do with their points! Indeed, there is now three new upgrades available in the Miner Vendor: 
1. A Lava-Proofing upgrade for 750 points, which is a direct upgrade to the Minebot's chassis to make it, you guessed it, lava-proof. 
2. A Speed upgrade for 750 points, overloading the Minebot's internal motors to make them 33% more efficient, resulting in a 33% increase in speed!
3. A Renaming board for 200 points, which allows the Minebot's owner to rename the Minebot to whatever they desire!

All upgrades also give user feedback when used on a Minebot, which was previously not the case, and there was also some weird typoes in them when they weren't able to be successfully applied, so Nanotransen fixed that as well.

## Why It's Good For The Game
Minebots are under-appreciated, both by people buying them and by people using them. This change should make it more enjoyable for both parties and will allow the Minebots to also have a function when their master is dead or dying, as their GPS signal can easily be tracked by anyone with a GPS, and all they have to do is to call for assistance over the radio, since they already have that functionality. Only thing that I've got to figure out at this point is how to change the GPS signal name when the Minebot gets renamed, but it's not that big of a deal.

## Changelog
:cl:GoldenAlpharex
add: Added Minebot Lava-Proofing Upgrade
add: Added Minebot Speed Upgrade
add: Added Minebot Renaming Board
add: Added GPS signal to Minebots
add: Added chat feedback to all upgrades upon successful applying said upgrades on Minebots
balance: Minebots are now ash-proof by default
spellcheck: Fixed a lot of typos in the chat feedback upon failure to apply the upgrades
admin: Added Admin chat feedback for when a Minebot gets renamed for ease of reference
/:cl:

### CODE REVIEW

**Comment by ATH1909** [comment]
you might wanna PR this on /tg/ as well

**Comment by GoldenAlpharex** [comment]
> you might wanna PR this on /tg/ as well

I was going to try and see what Fulp thought of it first, because I felt like this is the kind of thing that I'd need more knowledge on what /tg/ is like first before PRing it there too, since it might be a different kind of dynamic there? I don't know how /tg/ is and I don't want to make changes there that could affect others that aren't even concerned. I know that's a clumsy way of explaining things, but basically I don't feel comfortable doing game-changing stuff on a server I don't even play on. If you tell me people on /tg/ want it, then, sure, I don't mind, but I don't want to force it onto them.

**Comment by GoldenAlpharex** [comment]
Also, I'm probably going to have to close this PR and re-submit it again, as my local repo seems to be a weird hybrid of Fulp and /tg/, where all the extra files that Fulp has don't exist, but if the files exist on  /tg/ but have been modified on Fulp, then I'll have those modifications. Very weird.

**Comment by GoldenAlpharex** [comment]
I'm closing this PR because I'm re-uploading it with the right code in it.

The new PR can be found at https://github.com/TheSwain/Fulpstation/pull/392

**Pull request closed without merging**
