### PR TITLE
Adds devils back to event rotation.

### PR DESCRIPTION
**Pull request by ErwinSnowden**
## About The Pull Request

Does what it says on the tin.

## Why It's Good For The Game

Antagonist diversity, we used to have them but I guess they were removed for some reason (from normal rotation), this seeks to re-add them in event form where they can disrupt rounds (but not as much as a space dragon or ninja would), might devote myself to reworking devil if I get a spark of passion to.

## Changelog
:cl:
add: Devils can now appear due to random events, keep your eyes out security.
/:cl:

### CODE REVIEW

**Comment by JohnFulpWillard** [comment]
Devils were removed because it does nothing but encourage self antag and validhunting. People who want to self antag will rush to sell their souls to every single devil before getting their soul back from the lawyer, then greytide with AA with the help of the AI and the ability to one click stun anyone and a spell to open doors, ruining the round for anyone who didn't plan on self antagging

**Comment by ATH1909** [comment]
Devils are currently admin-only for a _reason_. Yeah, Devil rounds can be fun, but it's best to have them be a special thing rather than just another roundtype, as they have some balance (and/or design)... "issues". Sort of like how clock cults were removed from rotation, but kept as an admin-only thing for a while (before being removed from the code entirely due to no longer being supported, which was very sad).

**Comment by ErwinSnowden** [comment]
Would you both prefer if I made it rarer?

**Comment by Helianthus00** [comment]
We honestly don't even like when the other mods/admins trigger it. Devil rounds are a mess of self antag and just don't fit on Fulp at all. If you want to rework the entire gamemode, maybe we will consider adding it then but in it's current state, it will never be re-added to rotation.

**Pull request closed without merging**
