### PR TITLE
tweak the way phobetor tears are made

### LINKED ISSUE #304: return_valid_floor_in_range is highly inefficient
## Round ID:
[6412](https://scrubby.melonmesa.com/round/6412)

## Testmerges:
None

## Reproduction:
image
When determining efficiency using the profile, it's recommended to compare the Self CPU to the number of Calls. In the screenshot, the ratio of Self CPU to Calls for /proc/return_valid_floor_in_range is pretty bad. This proc is defined in code\FulpstationCode\fulp_procs.dm and is used in the code for beefmen's phobetor tears. @TheSwain if we get some time we should investigate how to better optimize this.

### PR DESCRIPTION
**Pull request by remove32**
basically want to randomize it properly so that we consume less memory. this is also more straightforward

## About The Pull Request
fixes #304 

## Why It's Good For The Game
better performing code should prevent memory exceptions and slowdowns

## Changelog
:cl:
fix: beefmen tears are randomly generated properly
/:cl:

### CODE REVIEW

**Comment by remove32** [comment]
@TheSwain i did testing on this just now and it worked like a charm

**Comment by Coolsurf6** [comment]
pog

**Comment by Samuuu3** [comment]
pog

**Comment by TheSwain** [comment]
Let's blaze this baby

**Comment by remove32** [comment]
@TheSwain a side effect of this is that tears sometimes will fail to spawn. just so you know

**Pull request merged**
