### PR TITLE
Adds the beautiful russian language to the wearer of the ushanka

### PR DESCRIPTION
**Pull request by SkippuSetsuna**
## About The Pull Request
Allows the ushanka to bestow you the Russian Language to speak and understand beefmen.

## Why It's Good For The Game
Makes some intresting interactions with beefmen for anyone that isn't a beefman

## Changelog
:cl:
add: When you put on the ushanka, it'll allow you to speak Russian as the beefmen do
/:cl:

### CODE REVIEW

**Comment by Homingpenguins** [comment]
can drones on the derelict speak it as well?

**Comment by SkippuSetsuna** [comment]
> 
> 
> can drones on the derelict speak it as well?

Didn't test it on drones, but assuming it would, even Ian too.

**Comment by Fikou** [comment]
> > can drones on the derelict speak it as well?
> 
> Didn't test it on drones, but assuming it would, even Ian too.

you check for humanity so how the fuck would it work

**Comment by Shadowtail117** [comment]
I think it should only apply to humans anyway. Animals or drones being able to communicate with humans when the shouldn’t be able to normally would imbalance the game.

**Comment by ATH1909** [comment]
Can't sapient animals speak common anyway?

And I think drones being able to speak Russian is probably fine; they can talk to curators and pAIs anyway.

**Comment by Shadowtail117** [comment]
Only simple mobs that players normally aren't controlling can speak Common. Monkeys, drones, etc. all have their own specific language.

Given beefmen know Russian, this gives them an unfair advantage, letting them converse with these simple mobs when only the Curator should.

**Pull request closed without merging**
