### PR TITLE
[READY] Safehouse Shuttle

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

This PR adds a new shuttle, the Safehouse Shuttle! More reinforced than standard shuttles, its compartmentalized rooms ensures utmost safety for those who wish to go to CentComm in it. All doors have been made Vault doors and walls replaced with Plastitanium. It comes at a steep cost of 20,000 Cr.
image

Creds to Hobo Joe for the idea

## Why It's Good For The Game

Variety is always good, and having a middle ground between the Raven cruiser and standard shuttle will aid Captain's in choosing the right shuttle for the job

## Changelog
:cl:
add: Added shuttle
/:cl:

### CODE REVIEW

**Comment by TheSwain** [comment]
/datum/map_template/shuttle/emergency/safehouse  can be defined in an existing (or even brand new) .dm file in the FulpCode folder. Any time you can avoid editing a TG file, you absolutely must.

**Comment by ghost** [comment]
Ill move it to FulpCode, thanks for letting me know!

**Comment by ghost** [comment]
@TheSwain Ive moved the /datum/map_template/shuttle/emergency/safehouse to its own dm in FulpCode, ill be testing it out now. Should be ready for merge.

**Comment by remove32** [comment]
image
uhhh

**Comment by ghost** [comment]
@remove32 Old image, this was fixed.

OR room was also switched with medbay.

**Pull request closed without merging**
