### PR TITLE
Drink Addition/Patch Stuff (Youtubeboy139)

### PR DESCRIPTION
**Pull request by Youtubeboy139**
## About The Pull Request

This PR is for adding new drinks into the game and one new vending machine

## Why It's Good For The Game

Adds a bit more variety to drinks in this masterpiece of a game

## Changelog
:cl:
add: Added new vending machine
add: Added new copious amount of canned drinks (both alcoholic and soda alike)
patched: Old Nuka Cola sprite work to make better sense. A new bottle sprite that matches other bottle designs in-game and will be vended from vending machines. A new animated glass sprite has been added for the mixed drink.
add: New Kvass drink to Soviet Soda vendor (10 units)
add: Hades Hellfire mix drink to fit the theme of the discord server pfp gag currently
add: Hairy Dairy mix drink at request of fellow discord person. Mix Manly Dorf and Cream for an awful, vomit-inducing concoction that will buff fireloss better than Manly Dorf.
add: New drink reagents - Bepis, Kvass, lager, lagger lager (WIP - not implemented in-game), IPA, guiness, and spacecastle
/:cl:

### CODE REVIEW

**Comment by gonenoculer5** [comment]
Why was this closed and reopened just out of curiousity. Ill be doing a code review on this here in a few minutes to see if everythings sound,  but from the quick once over it looks good 👍

**Comment by Youtubeboy139** [comment]
> Why was this closed and reopened just out of curiousity. Ill be doing a code review on this here in a few minutes to see if everythings sound, but from the quick once over it looks good 👍

It's my first PR and I forgot to add a changelog to the description and I thought you had to close it to edit it. I later learned that was not the case. Also, I'm not entirely sure if all the code bases needed are in here because I did them all on my computer via a downloaded master. I _think_ I got them all, but I'm a little skeptical about it. There were no errors when I compiled it, but still. All additions I made to the code are clearly marked and dated for your convenience. Simply search for //ADDITION in any of the files. Thanks for reviewing it! :)

**Comment by remove32** [comment]
will need to test this one to make sure everything looks good. will get back with ya later

**Comment by Youtubeboy139** [comment]
> will need to test this one to make sure everything looks good. will get back with ya later

Awesome, tell me if there are any errors you come across when you test it. There's nothing complex, it's mainly a copypasta so it's nothing earth-shattering, the most complex things are the mix drinks and they're as basic as I could make them. Again, I _might_ have missed some code transfer which is the only thing that would really cause problems, tests I did went without issue. Still, let me know and I'll pick it apart and see what I missed. Thanks again for reviewing this!

**Comment by remove32** [comment]
encountered a problem
vending machine doesnt kill me

**Comment by Youtubeboy139** [comment]
> encountered a problem
> vending machine doesnt kill me

If you mean it doesn't tip over when you hit it, it does, At least when I went in and tested the code.
I don't know what you mean by it not killing you, is there a separate code I didn't add? 

Annotation 2020-01-31 174459

As you can see, it crushed me just fine, I don't know what's wrong...

**Comment by remove32** [comment]
possible that another testmerge fucked that up. when i tested though it broke all the vending machines

**Comment by Youtubeboy139** [comment]
>possible that another testmerge fucked that up. when i tested though it broke all the vending machines

Ah, alright, thanks for the update. I looked through the code for a bit and saw nothing that stood out for error. I don't know how it would even effect the machines tipping over. Save for the sprite, the code is practically identical to all the other cola machines.

**Pull request closed without merging**
