### PR TITLE
Adding two new lobby songs

### PR DESCRIPTION
**Pull request by GaryGreytide**
### Hey, it's Gary
This is just a simple little PR that adds these two bits of music I made for Fulp. I sincerely hope the community enjoys in place of the classic lobby songs. To spice things up a bit, y'know?
### 
### About The Pull Request
A very simple addition of two, count em' TWO, original songs to spice up the lobby and add variety to fulp's rounds. It isn't fixing and reworking cloning to make it balanced and enjoyable, and it sure as heck isn't fixing clock cult, but it is something made for the community to enjoy in earnest. **Hope you enjoy :^)**

### Why It's Good For The Game
A few bits of music to freshen up and add variety to the lobby and game as a whole couldn't hurt, and hopefully will prove to be well received. It isn't intended to be a replacement for the Fulp lobby tunes, but if they are liked and enjoyed could become regular substitutes. That sort of thing should be up to the community at large and not me or any group of coders/devs alone. **Power to the people, yo.**

Changelog
🆑
add: Added new things
soundadd: added TWO new sound things
/🆑

_

> dad i did it, i am a coder

_

### CODE REVIEW

**Comment by EgorDinamit** [comment]
I think you forgot to actually add those in code, so they actually play in lobby.

**Comment by GaryGreytide** [comment]
> I think you forgot to actually add those in code, so they actually play in lobby.

i put it in sound, does it go in ambience?

**Comment by GaryGreytide** [comment]
> > I think you forgot to actually add those in code, so they actually play in lobby.
> 
> i put it in sound, does it go in ambiance?

fuck it i popped them in ambiance lol

**Comment by GaryGreytide** [comment]
> This PR has been inactive for long enough to be automatically marked as stale. This means it is at risk of being auto closed in ~ 7 days, please address any outstanding review items and ensure your PR is finished, if these are all true and you are auto-staled anyway, you need to actively ask maintainers if your PR will be merged. Once you have done any of the previous actions then you should request a maintainer remove the stale label on your PR, to reset the stale timer. If you feel no maintainer will respond in that time, you may wish to close this PR youself, while you seek maintainer comment, as you will then be able to reopen the PR yourself

Please no i don't wanna go to brazil

**Pull request closed without merging**
