### PR TITLE
Halloween Costumes

### PR DESCRIPTION
**Pull request by TheTeenyTiny**
## About The Pull Request
Halloween costumes

## Why It's Good For The Game
It'll be fun

## Changelog
:cl:
add: Added new costume sprites
add: Added new costume icon sprites
code: Added new code for Sailor Moon and Tuxedo Mas Costumes
/:cl:

### CODE REVIEW

**Review by AtlasRules — COMMENTED** [review]
tuxedo is spelt wrong in a couple of places. and weird capitalisation, but aside from that, good

**Comment by TheSwain** [comment]
Hi there! Mind if we get a screencap of the sprites so I can know what's going in before we merge! THX! <3

**Comment by TheTeenyTiny** [comment]
dreammaker_HGpyYh9S3N
dreammaker_CnTf0kp2Vu

And I think I caught all the spelling errors, I wish there was spell check in these programs T_T

**Comment by TheTeenyTiny** [comment]
Oh, and I haven't coded the rest of the sprites yet, but I'll be getting around to it eventually

**Comment by TheSwain** [comment]
lemme know when you have and i'll merge this bad boy all at once

**Comment by TheTeenyTiny** [comment]
I think I've got it all done : D

**Pull request merged**
