### PR TITLE
Fulp Emag Nerf

### PR DESCRIPTION
**Pull request by Surrealaser**
:cl:
add: New traitor item added: Budget Emag. Has 2 charges. 30 seconds after a charge is used, it regains a charge.
tweak: Standard Emag still exists but its TC cost has been increased to 15.
/:cl:

### CODE REVIEW

**Comment by ATH1909** [comment]
What, exactly, does this change "fix"?

**Comment by Surrealaser** [comment]
@ATH1909 The fact that emag is ridiculously overpowered for its price.

**Comment by ATH1909** [comment]
Emags are intentionally underpriced, IIRC.

How, exactly, would this PR make emags less overpowered? What (of note) could emags do before that they can't now with this PR in effect?

**Comment by Surrealaser** [comment]
@ATH1909 Deliberately underpriced according to who?

And if they are that's a dumb decision.

One of the main objectives of this change is to penalize and discourage indiscriminate use of the emag which this does.

Second, by indexing uses to time, it makes infiltration into high security areas that involve multiple airlocks and secured elements, like lockers, riskier; you can't just pop in and out anymore, or otherwise blitz through secure areas with casual ease. It is easy enough to tweak and adjust the number of charges and cooldown as needed.

**Comment by Homingpenguins** [comment]
I like the ballence aspect of this. And im at least happy that you made a cheeper alternitive then just raising the price and leaving it at that. Which would have been easier. Also, having the b-emag (budget emag) be 1 less tc would give many more traitor combinations, which were probably avoided on purpose with the 6 tc. But it doesnt do so anymore with this new emag. It also now gives meaning to double doored areas. Which i like.

**Comment by Homingpenguins** [comment]
I Just suggessted this to add diversity to the traitors toolbelt so they have slightly more to play with. This will turn things in slight favor of the traitor, basicly undoing part of the nerf.

**Comment by TheSwain** [comment]
I like the concept and I'll get to merging ASAP, after testing the recent TG update

**Pull request merged**
