### PR TITLE
Adds a medal box for engineering and medical

### PR DESCRIPTION
**Pull request by AtlasRules**
## About The Pull Request

Adds a medal box and and two new medals to the CMO and CE locker.

## Why It's Good For The Game
every department can now be rewarded with medals.

#
## Changelog
:cl:
add: Added a medal box to the CE and CMO locker with unique medals for both departments.
/:cl:

### CODE REVIEW

**Comment by TheSwain** [comment]
Are these files both new? If so, make sure to name them with something that designates they are for our server (accessories_fulp or something). Also, their location isn't good - make sure they go into appropriate folders and aren't floating around in the root.

**Comment by AtlasRules** [comment]
will do

**Comment by AtlasRules** [comment]
should be good now

**Comment by remove32** [comment]
think the icons are busted chief
also the boxes arent in the lockers
also theres a typo in the name "doctor of the shift award" award
image

**Comment by AtlasRules** [comment]
weird, worked fine on my end

will have a look

**Comment by AtlasRules** [comment]
try now, the icon_state was referencing an icon that didn't exist @remove32

**Comment by remove32** [comment]
that'd probably do it. I'll test when I get home

**Comment by TheSwain** [comment]
i don't see any code that places the medals box inside a locker anywhere. right now it looks like they need to be admin spawned

**Comment by AtlasRules** [comment]
Ah right, forgot to include that part of the code, my bad

**Comment by AtlasRules** [comment]
you can tell I was very tired when making this pr cant you

**Comment by AtlasRules** [comment]
i think
t h i n k
this is ready

**Comment by remove32** [comment]
fail
you never specified the icon file. the state means nothing 
do this 
image
the spawning in lockers does work though


also, tick your med_eng_medalboxes_fulp.dm file. and maybe change its name to something that can be more generic, in case we add more medalboxes later on. fulp_medals or something

**Comment by gonenoculer5** [comment]
^This shit gets me every time, its why i switched to using vscode since it autoticks new files if youve got the right extentions, also yeah generalize the name to fulp_medals like wind said, i might grab this and do some thorough testing, has anyone checked if the end of round report shows the rewards?

**Review by gonenoculer5 — APPROVED** [review]
Everything looks good, however I dont see any code referencing to it being awarded at the end of the shift, but that might be self-handling with the root item, not sure how medals are handled. Nice job!

**Comment by AtlasRules** [comment]
thanks dad

**Pull request merged**
