### PR TITLE
Moth wings 2, time to cry edition.

### PR DESCRIPTION
**Pull request by GuillaumePrata**
## About The Pull Request
Second try at the Moth wings

## Changelog
:cl: Guillaume Prata/Papaporo Paprito
add: New Moth wings sprites because customization is good.

/:cl:

### CODE REVIEW

**Comment by Samuuu3** [comment]
After the changes to the code this no longer works anymore. Can anyone tell Guill why?

**Comment by remove32** [comment]
you forgot to tick the file in the dme

**Comment by GuillaumePrata** [comment]
Odd because it worked worked on my end but I'm also github dumb, is it something you can fix or do I need to reupload the file and do something else?

**Comment by remove32** [comment]
add `#include "code\FulpstationCode\moth_wings.dm"` below `#include "code\FulpstationCode\medals_fulp.dm"` on the dme

**Comment by Samuuu3** [comment]
@GuillaumePrata We need the conflicting files fixed

**Pull request closed without merging**
