### PR TITLE
Removes Cat Ears.

### PR DESCRIPTION
**Pull request by ErwinSnowden**
Removes Cat Ears.
## About The Pull Request

Removes (most) instances of cat ears in the game.

## Why It's Good For The Game

Recently, I got banned because I beat up an individual wearing these, making it hard to get mitigates my rage and it's just plain degeneracy.

## Changelog
:cl:
del: Cat ears are gone, reduced to atoms.
/:cl:

### CODE REVIEW

**Comment by TheSwain** [comment]
Not sure we wanna start tampering with TG files just to get rid of a harmless meme. 

I'd rather make them self destruct on wearing them or something than removing them from the code - this futureproofs it in case TG messes with the item in the future.

THOUGHTS??

**Comment by ErwinSnowden** [comment]
Honestly, I don't know how to do that and it's rather unlikely that they'll further change cat ears anyhow. Furthermore, the kitty ears code is actually something that gets changed(since it's under misc special), so that's more likely to cause merge conflicts than just removing their instances in-game.

**Comment by TheSwain** [comment]
It's not about changing cat ears - it's about sweeping changes to the way datums and atoms function in their engine, which happens every few months. Every change to their code is a ticking timebomb, and I'm reluctant to make future work for myself resolving conflicts/bugs for something that isn't a cool new feature for the server.

Just removing the ears isn't a feature, but having them do something new would be.

**Comment by ErwinSnowden** [comment]
OK, in that case, I suppose I should make it function as the brain tumor quirk does when worn, which at the moment I'm not adequately educated enough to do, in part because I was banned from the discord for little reason regarding any infraction made on the discord but more-so actions on the server which (in my opinion) were acceptable for an LRP environment.

**Comment by TheTeenyTiny** [comment]
I think "Recently, I got banned because I beat up an individual wearing these, making it hard to get mitigates my rage and it's just plain degeneracy." Is a pretty bad reason to want to remove/change something that other people enjoy just because _you_ don't like it.

**Comment by CosmicPhoenix** [comment]
I don't think they should be removed; they're a harmless gag item that almost never gets used and on the occasion they do no one suffers. They only cause problems when people decide that using them is "degeneracy" for no good reason.

**Comment by remove32** [comment]
I dislike this PR greatly, not just because its someone I don't know (I believe this may be jeff but not sure), but its a PR to remove an item from the game just because they had a bad experience involving someone with cat ears.

**Pull request closed without merging**
