### PR TITLE
T5 parts

### PR DESCRIPTION
**Pull request by gonenoculer5**
## About The Pull Request

-Added new T5 parts based on quantum and bluespace combo tech
-Provides a new, final tier for stock parts that are a bit more costly than the others, but still mass produce-able
-Later PR will add code to possibly re-add the old trekkie chems as T5 chem recipes.

## Changelog
:cl:
add: T5 Stock parts (Capacitor, scanning module, cell, manipulator, laser, matter bin)
/:cl:

### CODE REVIEW

**Comment by gonenoculer5** [comment]
-Forgot to mention but if Swain agrees with this PR ill have them sprited by mith as their currently using the T4 part sprites as place holders

**Comment by ghost** [comment]
I'll throw together some sprites for this if it gets approved.

**Comment by TheSwain** [comment]
Hey bud - I'm going to review this change on my local machine asap before putting it live

**Comment by gonenoculer5** [comment]
Dope, let me know when your done, on disc pref

**Comment by remove32** [comment]
The material costs for these items are way too low. I'm also concerned about the possibility of breaking things with T5 parts... T4 are already super powerful. Testing should hopefully reveal the stability. Also, it'd be better to have distinguished icons prior to merging this. Just sayin

**Comment by ghost** [comment]
Like I say I'm gonna make unique icons for this if swain says it's good. We'll add them before it gets merged. I got a lot of spriting on my plate ATM and I dont wanna make smth if it's not gonna get used.

**Comment by gonenoculer5** [comment]
@remove32 Yeah I need to raise the material costs, I took them from some old-code apparently, ill be fixing them tomorrow or today, depends on if I can get VSC and all of my stuff for programming loaded onto my USB drive lol. Thanks for the feedback.

**Comment by TheSwain** [comment]
Okay sorry to take so long on this, shit's been going down round here.

Anyway, @gonenoculer5 can you move all of the new objects you made into a new .dm? Something like "t5_parts_fulp.dm" or "gonenoculer5_objects.dm" or something more descriptive so we can find all your changes in one spot.

This is important because future changes from TG can (and always will) result in merge conflicts, and putting them all in a new file together will ALWAYS be cleaner. <3

**Comment by ghost** [comment]
Is that a goahead on me to make the assets?

**Comment by TheSwain** [comment]
It depends - do we want to live test first and see what happens? What's missing if we do that?

**Comment by TheSwain** [comment]
Looking good - there are a couple of files where there are empty lines added/removed, and there's at least one spelling correction of a TG file. If you can wipe those changes, and merge that last object (/obj/item/stock_parts/cell/quantum) into your code/FulpstationCode/t5_parts.dm file, we'll be good to add this boy in.

*if you wanna correct TG spelling errors, better to do that on TG's side.

**Comment by ghost** [comment]
I'll make assets for this tommorow

**Comment by gonenoculer5** [comment]
-Closed due to github fuckin deciding to thanos snap it, refer to #96

**Pull request closed without merging**
