### PR TITLE
Fix for Sec Radios

### PR DESCRIPTION
**Pull request by Surrealaser**
Sec radios can no longer access the full spectrum.

Also all the white space that used to be in this code is now gone.

### CODE REVIEW

**Comment by JohnFulpWillard** [comment]
but then how am I supposed to speedrun command comms as deputy

**Comment by Surrealaser** [comment]
@TomFulpWillard steal it off a head; you have the tools

**Comment by ATH1909** [comment]
Can they listen to syndicate comms?

**Comment by Surrealaser** [comment]
@ATH1909 No.

**Comment by JohnFulpWillard** [comment]
I believe it's all channels but Syndicate. I've seen someone use it for the CentCom channel too

**Comment by Surrealaser** [comment]
@TomFulpWillard Per this PR it cannot access channels outside of the public range except for the randomly selected sec emergency channel.

**Pull request merged**
