### PR TITLE
Drinks Galore and plenty More! (Frank Mcfreely)

### PR DESCRIPTION
**Pull request by Youtubeboy139**
## Changelog
:cl:
Added various canned drinks (both soda and alcoholic in nature)
-Guinness
-Bepsi
-Astro Dew
-Cosmic IPA
-Iced Coffee
-Kvass
-Lagger Lager (Implemented but still WIP)
-Space Lager
-Spacecastle Black Ale
-Water
Redid Nuka Cola because let's face it the previous one wasn't very good
-Bottled Nuka Cola
-Animated icon for a glass of Nuka Cola
Added Bepsi Vending Machine
Added five flavors of White Claw
-Lime
-Cherry
-Mango
-Raspberry
-Grapefruit
Added Hairy Dairy mixed drink
Added Hades Hellfire mixed drink
/:cl:

### CODE REVIEW

**Comment by TheSwain** [comment]
Are all of these .dm files new?

**Comment by Youtubeboy139** [comment]
Yes, coded from a .ZIP file on my desktop through Dreammaker

**Comment by Samuuu3** [comment]
Ayeee Kvass.

**Comment by Youtubeboy139** [comment]
yee, figured another Russian delicacy was in order

**Comment by Youtubeboy139** [comment]
Saddly I'm going to have to close this PR because I forgot to add the vending_icon.dm so my new vending machine will be without a texture. Sorry, I'll redo this later...

**Comment by Youtubeboy139** [comment]
Saddly I'm going to have to close this PR because I forgot to add the vending_icon.dm so my new vending machine will be without a texture. Sorry, I'll redo this later...

**Pull request closed without merging**
