### PR TITLE
Improved Detective Default Kit

### PR DESCRIPTION
**Pull request by Surrealaser**
## About The Pull Request

This PR adds several new toys to the detective's default kit:

1: Detective scanner glasses. This has a meson and standard mode. Has integrated diagnostic, health and sec HUDS. Analyzes reagents. Can be made in the protolathe but requires sec access and is expensive. It is not flashproof despite appearances.
2: Detective PDA cartridge gains access to atmospheric and reagent scanning functionality.
3: Detective starts with crew pinpointer and portable crew monitor for help tracking suspects/sec personnel/victims.
4: Detective starts out with a fully loaded high capacity detective camera and universal recorder.
5: Forensic scanner now has a biochem scanner mode that scans reagents in a body and has the functionality of an advanced health scanner and can scan objects for their reagent/chem contents. Cost of manufacture has been increased to compensate for additional functionality. Records of all scans are saved to the scanner's log and can be printed.

## Why It's Good For The Game

Substantially improves the detective's ability to fulfill his role and do his job, giving him immediate and guaranteed access to much needed tools.

## Changelog
:cl:
add: Detective default kit expanded, and now includes detective scanner glasses, a high capacity camera, universal recorder, crew pinpointer and portable crew monitor.
add: Forensic scanner now has a biochem scan mode that acts like an advanced health analyzer and chem analyzer; scan results are saved to its log and can be printed.
add: Detective scanner glasses added: Features health, sec and diagnostic HUD and reagent scanning with toggleable mesons. Can be temporarily disabled with EMPs. Is not flash proof.
/:cl:

### CODE REVIEW

**Comment by ATH1909** [comment]
You might want to change the sprite of detective scanner glasses to something more resembling a medHUD or a diagnosticHUD, so that people won't get confused and think that it has flash protection (yes, you mentioned that in the changelog, but will people who join a month from now read an old changelog?).

**Comment by Surrealaser** [comment]
@ATH1909 I want to retain the sunglasses aesthetic though.

**Comment by TheSwain** [comment]
I added a few // FULP  comments on a few lines in case TG ever changes them, we'll get a conflict and can update.

Will merge after conflict resolution

**Comment by TheSwain** [comment]
Good to go?

**Comment by Surrealaser** [comment]
@TheSwain Seems so.

**Comment by Surrealaser** [comment]
@TheSwain Conflicts resolved and the PR has been brought up to standard.

**Comment by Surrealaser** [comment]
@TheSwain Conflict resolved

**Comment by Surrealaser** [comment]
Conflicts fixed again

**Comment by Surrealaser** [comment]
@TheSwain Is there anything further you need done before merge?

**Pull request merged**
