### PR TITLE
Suffocating carbons can no longer speak

### PR DESCRIPTION
**Pull request by Shadowtail117**
## About The Pull Request

If a carbon mob failed their last breath (they're being strangled, there's not enough oxygen, etc.), then they will not be able to say anything and instead a warning saying "You can't breathe and can't speak!" will appear in their chat window.

## Why It's Good For The Game

This makes speaking more realistic, as if there is no air in your lungs, you can't vibrate your vocal cords to say anything. Plus, this creates an incentive for "stealth" takedowns—if you are able to strangle your target or otherwise make them suffocate, you can make a silent takedown since now they can't alert the rest of the crew.

## Changelog
:cl:
add: Carbon mobs that are suffocating can no longer speak.
/:cl:

### CODE REVIEW

**Comment by Shadowtail117** [comment]
I've already tested this on a private server* and it works perfectly. Though I would like some feedback on the warning message, if people like it or if it should be changed.

*I choked myself and couldn't speak. Should work for if there's not enough air as well, or if something else stops you from breathing.

**Comment by ATH1909** [comment]
Krav Maga's lung punch is now pretty much always better than throat chop.

Can wizards cast spells while suffocating? SHOULD wizards be able to cast spells while suffocating?

Won't this PR make lexorin even more of a gamer chem than it already is?

**Comment by Shadowtail117** [comment]
- I was originally planning on making people able to whisper even if they're suffocating, but I'm still trying to find out how I could implement that.
- Haven't tested it, but since wizards need to yell the spell, they shouldn't.
- That's one of the points of this PR, to make it so that if you can stop someone from breathing, you can stop them from speaking. It'd make stealth kills much more feasible and incentivized.

**Comment by remove32** [comment]
image

**Comment by Shadowtail117** [comment]
Hmm, it compiled fine for me. Though my fork is outdated a bit, let me update and try again.

**Comment by remove32** [comment]
its because you didnt tick the new file in the dme

**Comment by Shadowtail117** [comment]
Oh right...forgot that that was necessary when making new files. Lemme update that real quick.

**Comment by Shadowtail117** [comment]
what

i literally took the .dme straight from the master branch

how do i have 4 extra files

**Comment by remove32** [comment]
I think this can be improved by hijacking handle_breathing in life.dm

image

If true, add mute trait, else remove it?

**Review by remove32 — CHANGES_REQUESTED** [review]
see comment in conversation

**Comment by Shadowtail117** [comment]
That would be more efficient but then if they try to speak they might think they’ve been hit with mute toxin or something else, especially since we don’t have a changelog for Fulp edits so they won’t see this coming. I don’t think you can customize the mute message, either. If this doesn’t seem like big enough an issue to you I’ll go ahead and change it, though.

**Comment by Shadowtail117** [comment]
Plus (and I only realized this now), that would remove the mute trait even when it shouldn't be. Stuff like mute toxin, the mime's vow of silence, etc. would all be nullified by taking a single breath. 

If we went down this road we'd have to create a new status effect to describe these issues without affecting other sources of being muted, which I feel is unnecessary.

**Comment by remove32** [comment]
MUTE is a genetic mutation - carbon has the silent var that is not intrinsically connected
image
We can cheat a bit by checking what krav maga's neck chop does
image
we dont need to use clamp because we can just modify the var on successful or failed breath
here's where silent gets used 
image
say.dm invokes this proc to check if silent or not

**Comment by TheSwain** [comment]
I like this, lemme know @remove32 if any changes you were asking for have been completed

**Pull request closed without merging**
