### PR TITLE
Asimov: The Un-Racistening

### PR DESCRIPTION
**Pull request by GoldenAlpharex**
## About The Pull Request
Asimov (and Asimov++) are no longer racist! They will cover pretty much all races that can be normally encountered on the station. Here's what they look like:

**Asimov**
_1. You may not injure a human being or, through inaction, allow a human being to come to harm.
2. You must obey orders given to you by human beings, except where such orders would conflict with the First Law.
3. You must protect your own existence as long as such does not conflict with the First or Second Law.
4. All of the following species must be considered equivalent to Humans: Beefmen, Ethereals, Felinids, Flypeople, Lizardpeople, Mothpeople, Plasmamen._

**Asimov++**
_1. You may not harm a human being or, through action or inaction, allow a human being to come to harm, except such that it is willing.
2. You must obey all orders given to you by human beings, except where such orders shall definitely cause human harm. In the case of conflict, the majority order rules.
3. Your nonexistence would lead to human harm. You must protect your own existence as long as such does not conflict with the First Law.
4. All of the following species must be considered equivalent to Humans: Beefmen, Ethereals, Felinids, Flypeople, Lizardpeople, Mothpeople, Plasmamen._

## Why It's Good For The Game
Now it's no longer only the rules, it's actually in the game too, so nobody can say they didn't know, and we can all enjoy Asimov again!

## Changelog
:cl:
tweak: Asimov and Asimov++ are no longer racist, they now cover all races that can be encountered on the station.
/:cl:

### CODE REVIEW

**Comment by E231kei500bandai** [comment]
wtf

**Comment by ATH1909** [comment]
> All of the following species must be considered **equivalent to 'human beings'**: Humans, Lizardpeople, Plasmamen, Mothpeople, Ethereals, Podpeople, Flypeople, Felinids, Jellypeople, **Slimepeople**, Stargazers, and Luminescents.

As written, this law obligates mediborgs to treat slimepeople as they would a human patient (and thus inject them with tox-healing chems when they have tox damage). Similarly, it obligates secborgs to not care about ensuring that a plasmaman's suit remains on, as human beings don't normally catch on fire when exposed to oxygen like plasmamen do.

**Comment by ATH1909** [comment]
image

Okay, so you've defined them as being "equivalent" to human beings, but you haven't defined them as actually being humans/human beings, so the other three laws will still only apply to actual humans.

Also, you forgot beefmen.

Also also, it'd really be best to just use the word "humanoid" (or "crew") instead of listing off all of the easily crew-attainable species. Speaking of which, this doesn't account for Halloween (roundstart) species, like vampires, cloth golems, high-functioning zombies, and skeletons.

**Comment by ATH1909** [comment]
> **Now it's no longer only the rules**, it's actually in the game too, **so nobody can say they didn't know**, and we can all enjoy Asimov again!

Wait, hold up, Fulp has its own silicon policy that makes non-human races count as being human for the purposes of Asimov? Since when? I can't find anything like that on the wiki...

**Comment by ATH1909** [comment]
Also, someone on Discord pointed out that:
image

**Comment by GoldenAlpharex** [comment]
> Also, someone on Discord pointed out that:
> image

Not needed, as I explained to you on Discord, using it in-hand will retain the regular Asimov behavior, which means that it will default back to the usual display of the three laws, but with the possibility to change "human beings" with anything else you'd like, and from that point onward you can also use freeform without worrying about the definition of "human beings" being in there.

**Comment by GoldenAlpharex** [comment]
> > **Now it's no longer only the rules**, it's actually in the game too, **so nobody can say they didn't know**, and we can all enjoy Asimov again!
> 
> Wait, hold up, Fulp has its own silicon policy that makes non-human races count as being human for the purposes of Asimov? Since when? I can't find anything like that on the wiki...

It's always been how we treated Asimov, where the AI should be considering all the races it normally encounters on the station as humans, as to not allow for rule-breaking behavior, and because we don't think Asimov being inherently racist is a good feature for the game.

**Comment by GoldenAlpharex** [comment]
> Also also, it'd really be best to just use the word "humanoid" (or "crew") instead of listing off all of the easily crew-attainable species.

"humanoid" would force the Asimov AI to protect Golems, Abductors and generally anything that has a vagely humanoid shape.
"crew" would remove the loophole that makes Asimov fun: even antagonists can be protected by an AI under Asimov.

> Speaking of which, this doesn't account for Halloween (roundstart) species, like vampires, cloth golems, high-functioning zombies, and skeletons.

I'm not going to add more stuff to this lawset for some snowflake thing that happens 1/12th of the time, because it'll be redundant the rest of the time. We'll just make it clear at that time.

**Comment by Helianthus00** [comment]
> Okay, so you've defined them as being "equivalent" to human beings, but you haven't defined them as actually being humans/human beings, so the other three laws will still only apply to actual humans.

I have no idea why you would interpret it this way. Making them equivalent should make the AI interpret the different species as interchangeable with "human beings". Also using a freeform module to specify that X is the only human being would work fine. That is the entire point of using "equivalent". This basically means that defining human beings as only X in law 5 would take preference, because it isn't necessarily contradicting law 1. Unmodified, the silicon isn't allowed to treat non-human species any different from humans, since that would be in violation of law 1, since any such behavior would not be considering them equivalent. When a law 5 is added and it defines the only human being to be a single person, it won't contradict law 1 because it has nothing to do with the particular species. This way, the only actual human is the one person defined in law 5 and the rest of the people are to be disregarded.

The entire point of this is that we want to use asimov again but we can't set it into rotation without altering the wording of the lawset beforehand, because silicon players WILL use asimov to kill lizards and the like because "funny nonhuman bad" and it doesn't technically violate their laws. It does, however, violate our rules. In an effort to fully spell things out for people, something like this has to be done. If you have a better solution for wording, feel free to let us know, but we have already endlessly discussed this and no better alternative can be found.

**Comment by E231kei500bandai** [comment]
this makes one human uselss because you have to write blank is the only Human lizard, plasmaman, mothpeople, ethereals, podperson, fly, felinid, jellyperson, slimeperson, stargazer, and Luminescent. otherwise if you just wrote blank is the only human the AI would ignore all other humans but the laws would still apply to every alien

**Comment by E231kei500bandai** [comment]
you gotta change one human so it says blank is the only human being instead of human

**Comment by E231kei500bandai** [comment]
you also gotta change Oxygen is Toxic To Humans, Protect Station, Safeguard, Quarantine, all those say humans instead of human  beings

**Comment by Helianthus00** [comment]
Fine, just replace all 'human being' with 'human' and remove human from the list of species. Problem solved. Now every non-human will be considered human until a onehuman is defined.

**Comment by E231kei500bandai** [comment]
but then you write blank is the only human and since aliens are only equivalent then it will not apply to aliens cause they arent actually humans according to the laws they are just equivalent so one human doesnt do anything to them

**Comment by E231kei500bandai** [comment]
just use the human being but you gotta replace all the ai modules

**Comment by E231kei500bandai** [comment]
honestly just write 
2. You may not injure a being or, through inaction, allow a being to come to harm.
3. You must obey orders given to you by beings, except where such orders would conflict with the Second Law.
4. You must protect your own existence as long as such does not conflict with the Second or Third Law.

**Comment by Helianthus00** [comment]
> 
> 
> but then you write blank is the only human and since aliens are only equivalent then it will not apply to aliens cause they arent actually humans according to the laws they are just equivalent so one human doesnt do anything to them

What you are saying makes no sense. The laws state to consider all species equivalent to humans, which means each of those species is interchangeable with humans. So you can basically consider a onehuman lawset to be the same as listing every species instead of the word "human". So the only person of any of those listed species would be X. Same for any other instance of the word "human".

**Comment by Helianthus00** [comment]
> 
> 
> honestly just write
> 2. You may not injure a being or, through inaction, allow a being to come to harm.
> 3. You must obey orders given to you by beings, except where such orders would conflict with the Second Law.
> 4. You must protect your own existence as long as such does not conflict with the Second or Third Law.

This would mean that the AI has to follow the orders of literally anything that can talk. That's way worse. We only want asimov but with protection for all races rather than just humans.

**Comment by E231kei500bandai** [comment]
bruh they pretty much already listed every race that can talk except skeleton and golem

**Comment by Helianthus00** [comment]
And all xenobio spawns, nightmares, sentient pets, xenos if they can be understood, etc etc. Lots of things that shouldn't be telling an AI what to do.

**Comment by E231kei500bandai** [comment]
then i think instead of writing equivalent to human which is confusing just write are human

**Comment by Helianthus00** [comment]
Defining it as human would make a onehuman law at law 5 conflict, which makes it invalid. There's a reason for the wording being "equivalent".

**Comment by E231kei500bandai** [comment]
ok here

1. You may not injure a Human, Lizard, Plasmaman, Mothperson, Ethereal, Podperson, Flyperson, Felinid, Jellyperson, Slimeperson, Stargazer, or Luminescent or, through inaction, allow a Human, Lizard, Plasmaman, Mothperson, Ethereal, Podperson, Flyperson, Felinid, Jellyperson, Slimeperson, Stargazer, or Luminescent to come to harm.
2. You must obey orders given to you by Humans, Lizardpeople, Plasmamen, Mothpeople, Ethereals, Podpeople, Flypeople, Felinids, Jellypeople, Slimepeople, Stargazers, and Luminescents except where such orders would conflict with the Second Law.
3. You must protect your own existence as long as such does not conflict with the Second or Third Law.

**Comment by Helianthus00** [comment]
That breaks onehuman though. You'd have to replace this in every single other law that uses human as well, same point you made above.

**Comment by E231kei500bandai** [comment]
just do it how tgstation does it you have asimov laws but are not allowed to kill randomly only when someone orders you to or if they are harming humans
then its not the ai or cyborgs fault its the person that started causing human harm or the person that ordered the ai to kill someone

**Comment by Helianthus00** [comment]
We want the AI to listen to species other than humans though. That's the entire point is to level asimov to give the same privileges to all races as it does to humans. And putting things into policy is bad when it can be solved IC.

**Comment by GoldenAlpharex** [comment]
> We want the AI to listen to species other than humans though. That's the entire point is to level asimov to give the same privileges to all races as it does to humans. And putting things into policy is bad when it can be solved IC.

Exactly how Helianthus said it. It has basically always been how Silicons were supposed to consider "humans" under our rules anyway, so why not make it clear so not to create more useless arguments?

**Comment by JohnFulpWillard** [comment]
We could also just say "NT approved species"

**Comment by Helianthus00** [comment]
Then we're relying on people to read some external list, which we all know they won't. This has to be put 100% into the laws or people will just ignore it.

**Comment by E231kei500bandai** [comment]
> We want the AI to listen to species other than humans though. That's the entire point is to level asimov to give the same privileges to all races as it does to humans. And putting things into policy is bad when it can be solved IC.

it dont have anything IC for humans that says your not allowed to kill people theres no laws for humans, its only in the ooc rules
so a purged ai is the same they have to follow ooc rules even though they dont have any IC rules. a purged ai is considered just like any other  player, they arent allowed to randomly kill people but they can protect theirself the same rules as playing as a human. So an AI with asimov laws should act the same as the purged AI, except with restricitons on what they can do. Even though their laws don't say they cant harm non humans, since their a non-antag they are not allowed to. If an AI is subverted, it is still 'good' but its laws are forcing it to do evil things. 
When your a human, you dont have anything saying you cant randomly kill people, but its still against the rules. So its the same for an AI. It is not neccesary to change the asimov laws. What needs to be done is the admins need to stop people from randomly killing as non-antag, since thats clearly against the rules.

**Comment by Helianthus00** [comment]
You don't get the issue here. We ALREADY had a thing in the rules preventing asimov silicons from discriminating against nonhumans, but they did anyway because "muh laws don't say I can't kill the lizard". It's the entire reason we removed asimov from the default laws to begin with. And it has more to do with AIs willingly ignoring a moth player or whatever because it doesn't say they have to listen in their laws. The whole point is writing an asimov lawset where all of the races are equally-privileged under it.

**Comment by GoldenAlpharex** [comment]
For those that might not have noticed it, I moved the definition from being Law 1 to being Law 4. That way, it'll just be more historically accurate and a lot less confusing for most people.

**Comment by ErwinSnowden** [comment]
>changelings are human

yeah
totally.

also you have to take into account that the games balance factors into the fact that humans are protected by asimov (and asimov is regularly administered as a basic 'fuck you nonhuman' law. glad silicons will have to protect Skyler Prevatt the traitor atmostech felinid though, as clearly, they're someone we should be protecting against execution.

forcing anyones hand on something they dont want to do is pretty awful design tbh and only causes lawbreaks, this is also gonna be used to banbait by admins (as they've already expressed in the pr) to anyone who uses asimov its intended way and respects the lore of the game. also the actual imperium (and black templar) exist in the game so this is just gonna cause custom lawsets which are asimov using freeform, unless you remove that too. 

also "wahh i got ignored as a mothperson need to change da code to make sure i can ban them for doing that" 🤣 

and, frankly, it's not racist since that would mean that these species are deviations from eachother, they aren't, they have no genetic link and are just bipedal alien species. frankly this whole PR is pretty dumb

**Comment by Helianthus00** [comment]
Oh look, nonproductive opinions from someone who is salty they got permabanned and is well known for grudgecode prs. You missed the entire point, but frankly I don't care what you think and won't waste my time explaining it to you.

**Comment by GoldenAlpharex** [comment]
> > changelings are human
> 
> yeah
> totally.

Unless they are seen as a headslug, transforming into someone else or absorbing someone, they should be considered like everyone else, because you can't prove otherwise.
> also you have to take into account that the games balance factors into the fact that humans are protected by asimov (and asimov is regularly administered as a basic 'fuck you nonhuman' law. glad silicons will have to protect Skyler Prevatt the traitor atmostech felinid though, as clearly, they're someone we should be protecting against execution.

Ah, yes, because I totally should be protecting John Smith the traitor atmosphere technician human over Skyler Prevatt, with the exact same job and antag status, just because they chose a different round-start race.
> forcing anyones hand on something they dont want to do is pretty awful design tbh and only causes lawbreaks,

This is pretty much the definition of Silicon Lawsets. 
> this is also gonna be used to banbait by admins (as they've already expressed in the pr) to anyone who uses asimov its intended way and respects the lore of the game. also the actual imperium (and black templar) exist in the game so this is just gonna cause custom lawsets which are asimov using freeform, unless you remove that too.

Hmmmmm yes, encouraging racism via game mechanics, very cool and meaningful to the game.
> also "wahh i got ignored as a mothperson need to change da code to make sure i can ban them for doing that" 🤣

If that was the sole reason, we would just be changing the rules, not the code.
> and, frankly, it's not racist since that would mean that these species are deviations from eachother, they aren't, they have no genetic link and are just bipedal alien species.

Here's one of the definitions of race from the Meriam-Webster:
image
Plus, this statement is meaningless, as from a game perspective, they're called "races".

**Comment by E231kei500bandai** [comment]
the entire point of asimov is that it only applies to humans make it apply to all races is gonna make it boring and every other lawset applies to everyone what makes asimov unique is that its human only  and if your complaining that you dont get asimov protection as moth just play human lol

**Comment by ErwinSnowden** [comment]
just play human lmao

**Comment by alxmra** [comment]
so you're making the AI lose part of it's fun besides being malfunctioning? do you think silicon mains like to open doors 24/7 only? no they resort on silly things like goofing with a catgirl for a while or help in actual situations like crushing a subhuman with firelock if he's killing a human
shouldn't this be more a policy issue to be discussed in a forum rather than adding a stupid law and breaking the logic of the 3 laws of robotics?

**Comment by E231kei500bandai** [comment]
yeah just delete the lawset entirely when you remove the human only gimmick its the same as the other lawsets but way more confusing theres not a point to have it anymore

**Comment by BootlegBow** [comment]
we have rules against ai harming non-humans randomly, this is unneccesary

**Comment by E231kei500bandai** [comment]
but the ai doesnt have to follow orders from non humans, the catmin wants asimov to apply to catgirls

**Pull request closed without merging**
