### PR TITLE
CentCom Galactic Ban DB

### PR DESCRIPTION
**Pull request by ike709**
Ports https://github.com/BeeStation/BeeStation-Hornet/pull/2207

Admins will now be able to look up a player's bans from several other servers via the player panel.

My hope is that porting this to as many servers as possible will encourage more servers to make their bans publicly viewable so they can be included in this system. Direct access to a server's database is not required (or even supported).

Supported servers: 
* BeeStation 
* /vg/station
* OracleStation
* FTL13
* Fulpstation
* TGMC

Planned support that bobbah is working on:
* World Server
* Yogstation
* Halo: SSE
* Any other server willing to make their bans publicly visible.

API: https://centcom.melonmesa.com
Source: https://github.com/bobbahbrown/CentCom

## Changelog
:cl: ike709 and bobbahbrown
add: Admins can now see your bans on (some) other servers.
/:cl:

### CODE REVIEW

**Comment by ike709** [comment]
image

**Comment by Samuuu3** [comment]
I like this, how would it work since we dont have public bans yet?

**Comment by ike709** [comment]
All it does is send a GET request to the server hosting the API & all of the bans. Your own bans just won't be visible until they're made public and added.

**Comment by Samuuu3** [comment]
Sounds good to me, I'll bug Wind to make ours public too

**Comment by remove32** [comment]
what the fuck ike

**Comment by Samuuu3** [comment]
I test merged and all i see is "CentCom Galactic Ban DB: Disabled"
do i need to add a config or something?

**Comment by ike709** [comment]
@Samuuu3 You need to add the config changes I made to `config.txt` to your actual server config.

Then run the `Reload Configuration` verb.

**Comment by remove32** [comment]
> 
> 
> I test merged and all i see is "CentCom Galactic Ban DB: Disabled"
> do i need to add a config or something?

yeah, config.txt needs CENTCOM_BAN_DB https://centcom.melonmesa.com/ban/search

I'll handle it

**Comment by remove32** [comment]
lmao 
image
it works now

**Comment by Samuuu3** [comment]
imagesorry I didn't even look I was just trying to do it quickly cause I'm chillin with Penelope 😎

**Comment by JohnFulpWillard** [comment]
So notes and bans can follow you through servers now? On one hand it seems useful so people can know who is there just to grief, but on the other you might have someone just trying to get a fresh start on a brand new server after being a shitter on another and being treated exactly the same

**Comment by ike709** [comment]
Fulpstation bans now supported.

**Comment by ike709** [comment]
TGMC bans now supported.

**Comment by Samuuu3** [comment]
Fulp is labeled in the DB as LRP while we are MRP, could that be changed?

**Comment by ike709** [comment]
bobbah said he'd fix it.

That's unrelated to this PR.

**Comment by ErwinSnowden** [comment]
> lmao
> image
> it works now
hey uh could you like, not harass me? kay, thanks.
"Big Brother is watching you."

**Comment by remove32** [comment]
ty ike

**Pull request merged**
