### PR TITLE
Holobed Projectors Added

### PR DESCRIPTION
**Pull request by Surrealaser**
## About The Pull Request

Adds Holobed Projectors. These can be used to project an indestructible holobed made of hard light up to 4 tiles away. Only one bed can be projected per projector at a time. Using the projector while a bed is out will dismiss the existing holobed.

Currently these are only available in game for the medborg, replacing their rollerbed dock.

I will add a handheld version that can be made via the Medbay protolathe if/when I get sprites for it.

## Why It's Good For The Game

Removes the annoying collision from the roller bed which significantly impedes their use as an EMT transport option as anyone who has had it collide with someone in the halls and have it pushed 2+ screens away can attest.

## Changelog
:cl:
add: Holobed projectors have been added. An integrated version replaces the rollerbed doc on Medborgs.
/:cl:

### CODE REVIEW

**Comment by Kokojos** [comment]
Yes to this, borgs can finnaly drag people to safety and not make a ton of blood appear everywhere

**Comment by remove32** [comment]
you forgot to tick your new file in the .dme

**Comment by remove32** [comment]
couple questions - 
image
can you just have it default to 4 if they try to do more than 4?
also, and this one might be problematic, can you have it dispel after the bed and the borg are more than x tiles apart? 10 or so?

**Comment by Surrealaser** [comment]
@remove32 I considered having the holobed run a periodic check for distance, but figured it probably wasn't worth the processing resources. Also, I might just increase the range to 7.

**Comment by remove32** [comment]
yeah i was thinking about the processing time. you could have it check infrequently but ultimately since they can only put down one i think it probably doesnt matter much

**Comment by Surrealaser** [comment]
Just in general I'd rather minimize any performance load; the server already chugs at higher pops.

**Pull request merged**
