### PR TITLE
Removes CMO, CE and RD from the human_authority list

### PR DESCRIPTION
**Pull request by ghost**
image

## About The Pull Request
Nonhumans can now be CMO, CE and RD.

## Why It's Good For The Game
We might actually have rounds with some heads again.

## Changelog
:cl:
tweak: re-enabled nonhuman CMOs, CEs and RDs
/:cl:

### CODE REVIEW

**Comment by lifeyouristhis** [comment]
Human bad ligger good yes

**Comment by AtlasRules** [comment]
I tended to play captain and CE before the human head law was enforced, and not having human heads has drastically affected quality of command. We tend to get either no captain and HOP, or they're both comdoms who can't do their job. Many non-human players, including myself would love to be able to play head again._

**Comment by Paprito** [comment]
yee

**Comment by TacoSalad7** [comment]
Not having a captain, HOP or HOS have been some serious issues. No HOP, no jobs, no captain, no coordination. Allowing all heads to be non human would remedy this issue, as there were a lot of good non human heads that now no longer play heads.

**Comment by AtlasRules** [comment]
> Human bad ligger good yes

what input does this even give? sod off

**Comment by lifeyouristhis** [comment]
In few brief words I express my positive reaction towards the re-inclusion of multiracial heads and comment about overally negative impressions I had about single race heads we've been experiencing recently.

**Pull request merged**
