### PR TITLE
Hulk Nerf

### PR DESCRIPTION
**Pull request by Surrealaser**
:cl:
tweak: Standard power version that lacks stun immunity and immunity to damage slowdown. There is a full power version granted by spells/wishgranter that is identical to its current state.
/:cl:

### CODE REVIEW

**Comment by Surrealaser** [comment]
@TheSwain After having recently experienced some rounds ruined by mass hulk, I am resubmitting this.

**Comment by ATH1909** [comment]
> @TheSwain After having recently experienced some rounds ruined by mass hulk, I am resubmitting this.

For the third time, I might add.

Let it go, dude. Hulks are valid; if someone starts griefing with hullk, just kite them with ranged lethal weapons until they fall into crit (since hulks can't use guns). Hulk is supposed to be the pinnacle of genetics, and having access to hulk is one of the biggest advantages of being a human (especially on Fulpstation, where the AI isn't always on Asimov).

Just because YOU couldn't deal with mass hulkings doesn't mean that they're impossible to deal with or some kind of blight upon the game.

**Comment by ATH1909** [comment]
Wait a minute- you're not ONLY removing the stun and slowdown immunity from hulk, but you're incorporating the genetic instability 100 change as well?! What the hell, dude?

Also, this doesn't make hulks any easier to nonlethally detain as a sec officer (especially a new sec officer), since they can still break out of cuffs near instantly and they'll die horribly (and likely permanently) in less than a minute after being caught by you if you don't crit them or feed them mutadone somehow (boy oh boy, I sure do want to leave my life in the hands of a sec officer who might have never played geneticist before).

**Comment by ATH1909** [comment]
And you didn't even add the instability 100 thing to the changelog.

Also, there is no way in hell that absolutely gutting genetics hulk counts as a "tweak"; change that "tweak:" to "balance:".

**Comment by Surrealaser** [comment]
@ATH1909 There were 2 security facing a mob of hulks; one of them was a secborg. I'm just utterly done with this nonsense.

As to the genetic instability, that looks to be merge garbage.

Third, yes, making hulks stunnable obivously allows security to deal with them much more easily, even if it involves beating them to crit.

I know you like the idea of greentide causing mass chaos and self-antagging, but enough is enough; I'm putting an end to this.

**Comment by ATH1909** [comment]
Why are you removing the stun immunity instead of the wall smashing, then? The wall smashing is what makes greentiding so enticing, as it's super easy to use it to smash your way into a department instead of asking to be let inside. Remove that, and less people will greentide in the first place, meaning that you won't have to face entire mobs of hulks at once. Smashed walls also tend to give off a "the station has descended into chaos" vibe (similarly to how streams of blood everywhere also give off that kind of vibe), contributing to the "mass chaos" that you mentioned.

Another alternative solution would be to keep hulk as it is now, but only let hulk mutators work on people who have strength as a dormant mutation in their DNA. That way, you physically CAN'T hand out hulk to the entire crew, and instead can only hand it out to a few lucky people.

**Comment by Surrealaser** [comment]
@ATH1909 Because the important thing is for security to be readily able to stop and punish greentide when it gets uppity and abuses its power outside of emergencies. Greentide mobs aren't a problem so much when stuns and disables work on them (stun and disable immunity being at least as enticing as wall smashing).

**Comment by Fikou** [comment]
did you have a stroke while writing that changelog

**Comment by Surrealaser** [comment]
@Fikou What are you talking about?

**Comment by Toxici11i** [comment]
this makes hulks not only completely useless, but a detrimental perk to anyone who takes them. Please, reconsider this PR, take a step back and actually consider what this means

A) hulks are no longer stun immune
B) hulks now take damage slowdown
C) hulks are instantly beginning to monky/die of genetic instability

all of the hulk upsides (apart from the increased meele damage/wallsmashing - WHICH DOESNT MATTER DUE TO THEM NO LONGER BEING IMMUNE TO DISABLER/TASER STUNS) are now gone, and instead, hulk is now completely useless

congratulations. hulk is now a negative trait

**Comment by Surrealaser** [comment]
@Toxici11i That's not what this PR actually does. The lethal genetic instability isn't a thing; you should actually review the PR as it stands.

Further, Hulk does have pros and cons: greater melee damage, breaking out of cuffs and wall smashing at the cost of sounding like a shouting green retard, and losing use of certain weapons you won't be getting access to the vast majority of the time. And yes, those buffs are still relevant; it just means you can't laugh at Sec when they come to arrest you without lethals specifically.

The alternative is removing genetics accessible hulks entirely which I would gladly consider.

**Comment by Toxici11i** [comment]
`
//***************************************************************************
//** FULPSTATION HULK NERFS by Surrealistik Jan 2020 BEGINS
//---------------------------------------------------------------------------
//** Nerfs Hulk so it has lethal genetic instability.
//***************************************************************************`
as quoted from your own CL

**Comment by remove32** [comment]
we should test merge this before we commit it to master

**Comment by TheSwain** [comment]
Can we recap the changes this will make? I've never cared either way about Hulk mutation, but I wanna make sure this doesn't make kids screech.

**Comment by Surrealaser** [comment]
@TheSwain Basically Hulk now has a two variants, the first is hulk as it exists, the other is hulk as gained through genetics.

Hulk gained through genetics loses stun immunity and immunity to slowdown from damage.

**Pull request closed without merging**
