### PR TITLE
"Removes" the ERP gasps

### PR DESCRIPTION
**Pull request by CosmicPhoenix**
## About The Pull Request

Replaces the gasp files with empty sound files. Specifically the AI vox comma files.

## Why It's Good For The Game

A absolute ton of people don't like the gasps and wanted them removed. This is the easiest way to do it and shouldn't cause conflicts until they're updated by /tg/. And if they're updated chances are we'd want to try out the new sounds anyway.

## Changelog
:cl:

tweak: A large unidentified space anomaly seems to have removed the ability for people to hear gasps. Despite this inconvenience work will still continue aboard the station. ~NT

/:cl:

### CODE REVIEW

**Comment by TheSwain** [comment]
When do these voices fire off?

**Comment by AtlasRules** [comment]
Gasping in crit/from lack of oxygen

**Comment by CosmicPhoenix** [comment]
As Atlas said. They're disabled when using the emote manually to, and I quote, "... **avoid degeneracy** and spam". 

They're not super common in-game but they happen enough that people have been bothered by them. An easy way to cause it is by using empty internals.

**Review by Saliferous — COMMENTED** [review]
Why not have something such as a toggle-button for the gasping noises instead of completely removing them?

**Comment by CosmicPhoenix** [comment]
Because general consensus is that they should be removed and I have absolutely no idea how to do that. We lived without gasping sounds before though so it's not that big of a deal. Ideally we'd replace them with actual gasping but I have no idea how to find sound files on the internet.

**Comment by BLUREMOTE** [comment]
@CosmicPhoenix 
I think I got what u need
https://www.soundsnap.com/tags/gasp

**Comment by ghost** [comment]
Does this cause runtime errors when the code cant find the audio files?

**Comment by CosmicPhoenix** [comment]
> Does this cause runtime errors when the code cant find the audio files?

The code finds the audio files and runs them, they're just silent. I didn't do anything besides change the contents of the files.

**Comment by ghost** [comment]
Cool.

@TheSwain This all seems fine.

**Comment by CosmicPhoenix** [comment]
Bunch o' merge conflicts and /tg/ is messing around with these on their end. If they don't edit them in a way we like I'll go back through and suggest edits to them on their end.

**Pull request closed without merging**
