### PR TITLE
Adds DIO!

### PR DESCRIPTION
**Pull request by ErwinSnowden**
## About The Pull Request

Adds a DIO costume to the hacked autodrobe, an outfit complete with a journal and tarot cards [Select Equipment] not from the autodrobe nerd, along with adding Dio to the list of bloodsucker names. Sprites made by Mithrandalf.

## Why It's Good For The Game

Jojokes are the DNA of the soul.

## Changelog
:cl:
rscadd: Added a dio costume, sprite by mithrandalf.
rscadd: Added Dio to the list of possible bloodsucker names.
/:cl:

### CODE REVIEW

**Comment by Coolsurf6** [comment]
You thought it was coolsurf6 commenting, but it was I, DIO!

Anyway please get this fucking merged. I also noticed that a jojo hat was added on tg but could not find it on here. Did the swain man skip it?

**Comment by ErwinSnowden** [comment]
> You thought it was coolsurf6 commenting, but it was I, DIO!
> 
> Anyway please get this fucking merged. I also noticed that a jojo hat was added on tg but could not find it on here. Did the swain man skip it?

Delinquent hat is in the autodrobe, it's easily missed but it exists.

**Comment by ghost** [comment]
ite so this isn't gonna get merged as-is for a handful of reasons

First thing you gotta do is move the icons to a _fulp dmi file; for example there's already a shoes_fulp.dmi

the items themselves will also need moving to a _fulp dm file

if there isn't a file already, make one by creating a dm file with the same name and a _fulp suffix

you'll then need to set the variables of 'icon' and 'alternate_worn_icon' to the new dmi filenames (for the inventory icon and worn sprite respectively) - put the file strings inside ' SINGLE marks instead of double " speech marks

and then finally throw a fulp_item = TRUE on there

this is all stuff we gotta do being downstream

**Comment by ErwinSnowden** [comment]
any questions/suggestions?

**Comment by TheSwain** [comment]
Can you place all of the object code into one common file? Feel free to put it in /clothing/ or something if you're worried about it being misplaced in some random folder.  clothing_dio.dm or clothing_dio_fulp.dm or something like that would be perfectly sane.

I also have some concerns that the files that were changed, and then changed back, might still register as altered, which can be a problem. When you have everything working, it might be best to close this pull and re-commit all your new files.

Is there any way to get all your sprites into one .dmi file? We're creating a LOT of new files that are only being used for one sprite each. There is nothing wrong with using a single file for common stuff, and they're all outfit pieces so it's not a reach.

Finally, TG updated the alternate_worn_state icon to a different name. We just updated to the most recent TG, so you may want to pull that update and then see what that breaks with this.

**Comment by ErwinSnowden** [comment]
closing, going to try this again on another branch because my fork was outdated.

**Pull request closed without merging**
