### PR TITLE
PRIORITY: Tgui-Next Chem Master Patch

### PR DESCRIPTION
**Pull request by Saliferous**
## About The Pull Request
Unfucks the chem master after the tgui-next update.

## Why It's Good For The Game
Makes Chem Master bottles and medipens properly work now

## Changelog
:cl:
edit: UI jargon
/:cl:

### CODE REVIEW

**Comment by TheSwain** [comment]
TG Update left some conflicts.

I hate this bullshit with the tgstation.dme file, it really shouldn't be causing merge conflicts EVER.

**Comment by Saliferous** [comment]
> TG Update left some conflicts.
> 
> I hate this bullshit with the tgstation.dme file, it really shouldn't be causing merge conflicts EVER.

Go ahead and overwrite my version of it then, it doesn't matter to me. No new files were created.

**Comment by Saliferous** [comment]
The ChemMaster.js conflict, however, needs to be updated with my version.

**Comment by TheSwain** [comment]
Sorry @Saliferous got a couple merge conflicts to dick with before i can merge. i'm cleaning house this week and handling all PRs.

**Pull request closed without merging**
