### PR TITLE
Steal pets as traitor objectives

### PR DESCRIPTION
**Pull request by Buzzardman2**
So i basically revived this PR: https://github.com/TheSwain/Fulpstation/pull/258

Tested it to make sure it works and everything seems fine to me so hopefully this works well for the server!

### CODE REVIEW

**Comment by Samuuu3** [comment]
I'd be happy to see this come back. Just now the code has changed and we can pick animals up. Make sure it works without the pet carrier too!

**Comment by Buzzardman2** [comment]
That was an absolute chaotic mess but with some help i figured it out i think!

**Comment by Buzzardman2** [comment]
I did a lot of testing on this to make sure the objectives worked properly. Hopefully that it works well with the actual server! If anything pops up i'm super open to criticism and will work my best to fix it!

**Comment by Samuuu3** [comment]
Testmerged in the server and works like a charm. 
image

**Pull request merged**
