### PR TITLE
Removes Felinids

### PR DESCRIPTION
**Pull request by JohnFulpWillard**
## About The Pull Request

Felinids don't deserve to exist. Fun fact while editing the code, I found out that slamming a felinid on the table gives them a positive moodlet saying "They want me to play on the table!" which I find VERY against our ERP rules.

## Why It's Good For The Game

Hundreds of souls are being saved

## Changelog
:cl:
del: Removes Felinids
/:cl:

### CODE REVIEW

**Comment by FatCat919** [comment]
ADD THIS SHIT, DEATH TO FELINDS

**Comment by SGSDHSD-Enterprise** [comment]
god finally we can relax once this is merged

**Comment by FatCat919** [comment]
if it isnt merged, make felind valid

**Comment by SgtHunk** [comment]
speedmerge

**Comment by GoldenAlpharex** [comment]
Haha, no.

**Comment by ErwinSnowden** [comment]
Speedmerge.

**Comment by E231kei500bandai** [comment]
felinds bad but how is "They want to play on the table!" ERP??

**Comment by JohnFulpWillard** [comment]
> 
> 
> felinds bad but how is "They want to play on the table!" ERP??

You're bashing someone on a table and they think "Oh they want to play with me on the table!" in the generic felinid mindset that's fucking ERP

**Comment by JohnFulpWillard** [comment]
The world is too corrupt for such a PR. It will only return when the world needs it most.

**Pull request closed without merging**
